worldedit-core/src/main/java/com/boydti/fawe/object/schematic/Schematic.java, worldedit-core/src/main/java/com/sk89q/worldedit/function/operation/ForwardExtentCopy.java
I decided to stay with the stream construction because the list type is a wildcard, means we would either need to change that or to add a helper method (or use an Iterator to remove players).
Commits should be fine now too...
=> change entity list to ignore player when pasting

worldedit-core/src/main/java/com/sk89q/worldedit/command/UtilityCommands.java
This change will avoid the exception which was thrown for sizes less than 1.It now just set the size to 1 if it is less than 1. It won't remove any block as long as you aren't inside of the block.
I've adapted this from WE's code.
=> fix //removenear exception for size < 1

worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/io/SpongeSchematicReader.java
Fixes this error when trying to read a sponge schematic that contains tile entities or entities:
https://pastebin.com/um0ax14N
The NPE was thrown because the clipboard is initialized with size == 0 and only resized after setting the blocks, if any tile entities or entities exist in the schematic.
This does fix the CPUOptimizedClipboard and DiskOptimizedClipboard, the MemoryOptimizedClipboard is still fucked and stores random blocks.
=> fix NPE when reading sponge schematics with tile entities or entities

worldedit-bukkit/build.gradle
As discuseed in Discord, placing the Vault-API Dependency over the dummypermscompat fixes the compiling issue, even though this is still a sketchy issue
=> (dirty) Fix for VaultAPI build issue

worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/io/SpongeSchematicReader.java
Minor but important improvement to  #35 
With the 'else' statement here, if the schematic contains no entities or tile entities the dimensions of the schematic are never set, causing it to load as a nx1x1 column of blocks (which might be *very* long)
Tested this a fair amount, seems to work well.
=> Fix sponge schematics not correctly setting dimensions if there are no entities

worldedit-bukkit/src/main/java/com/boydti/fawe/bukkit/adapter/mc1_13/BukkitAdapter_1_13.java, worldedit-bukkit/src/main/java/com/boydti/fawe/bukkit/adapter/mc1_14/BukkitAdapter_1_14.java, worldedit-bukkit/src/main/java/com/boydti/fawe/bukkit/adapter/mc1_15/BukkitAdapter_1_15.java, worldedit-core/src/main/java/com/boydti/fawe/object/collection/LocalBlockVector2DSet.java, worldedit-core/src/main/java/com/boydti/fawe/object/collection/LocalBlockVectorSet.java, worldedit-core/src/main/java/com/boydti/fawe/util/ReflectionUtils.java, worldedit-core/src/main/java/com/boydti/fawe/util/ReflectionUtils9.java
This pr fixes Java 12+ compatibility due to the modifiers field being hidden in (standard) reflection methods.
Tested this on a Java 8, 9, and 13 server.
=> Fix Java 12+ compatibility

worldedit-core/src/main/java/com/boydti/fawe/util/Jars.java
At some point, the code for integrity checks of downloaded JAR files has been changed to use the Base64 hash digest representation rather than the hexadecimal representation. However, `.toUpperCase()` has been left in place, now ignoring the proper casing of the Base64 representation.
This is a bad idea because makes hashes easier to break/collide as a variety of potential SHA-256 digests match a case-*insensitive* Base64 representation.
I changed Jars.java to take the casing into account and updated the included digests with their correct casing. This makes the hash verification more secure. <sub>And while at it, I made sure to update the javadoc which still referred to hexadecimal digests.</sub>
=> Improve security of hash verification

worldedit-bukkit/src/main/java/com/boydti/fawe/bukkit/adapter/mc1_14/BukkitAdapter_1_14.java, worldedit-bukkit/src/main/java/com/boydti/fawe/bukkit/adapter/mc1_15/BukkitAdapter_1_15.java, worldedit-bukkit/src/main/java/com/boydti/fawe/bukkit/adapter/mc1_15_2/BukkitAdapter_1_15_2.java
**Fixes https://github.com/Spottedleaf/Tuinity/issues/17**
The issue is on my tracker since it's technically my code that's caused this issue, however the fix is simple and compatible with paper and below.
I run a fork of paper which replaces the visibleChunks and updatingChunks
field for gc performance reasons - visibleChunks is updated via
cloning updatingChunks, and at high chunk counts this causes gc issues
due to the humongous allocation it makes. Unfortunately the only solution is to
not clone the map (cloning is required for the thread-safety of the map) - which is why the field is removed.
Instead of BukkitAdapter_1_15_2#getPlayerChunk using the visibleChunks field,
it now uses a MethodHandle for PlayerChunkMap#getVisibleChunk. This method is
present on spigot & paper (only …
=> Workaround for replacing PlayerChunkMap#visibleChunks field

worldedit-core/src/main/java/com/sk89q/worldedit/EditSession.java
**Fixes #307**
Attempting to set a block below Y: 0 and above Y: 255 results in an out of bounds error which can spam console when pasting or stacking large amount of blocks and delay world edits from completing. This PR will simply skip setting blocks outside of the Y: 0-255 range.
=> Don't attempt to set blocks below 0 and above 255

worldedit-core/src/main/java/com/sk89q/worldedit/extension/platform/binding/PrimitiveBindings.java
Fixes `//pos1`, `//pos2`, and similar commands clamping incorrectly
**Fixes #369**
Fixes incorrect clamping that lead to `//pos1` and other Vec3 based commands being restricted to strictly positive integers.
=> Fix clamping issue

worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/WorldEditPlugin.java, worldedit-core/src/main/java/com/sk89q/worldedit/extension/platform/PlatformCommandManager.java
Fixes tab completion in all commands.
**Fixes #256**
Prior to this, tab completion was completely broken. It would either do nothing (try `//brush <tab>`), or throw errors (try `/brush <tab>`).
=> Fix tab completion

worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/WorldEditPlugin.java
use JavaPlugin.getResource() instead of JarFile.getEntry()
=> use JavaPlugin.getResource() instead of JarFile.getEntry()

worldedit-core/src/main/java/com/sk89q/worldedit/command/ToolCommands.java, worldedit-core/src/main/java/com/sk89q/worldedit/extension/platform/PlatformCommandManager.java
I was referring to the config "strings.json"
`
"fawe.error.no-perm": "You are lacking the permission node: {0}"
`
`
"worldedit.tool.navwand.equip": "Navigation wand bound to {0}."
`
=> Fixing wrong translation keys

worldedit-core/src/main/java/com/boydti/fawe/Fawe.java
**Fixes #355**
Correction to FastAsyncWorldEdit's invalid detection of JVM Architecture to System Architecture.
I have tested this for both 32 and 64 bit for Windows JVM and Java 8 Linux JVM environments. Both acted as expected, showing the mismatching architecture error. If any further operating system tests are required, just let me know.
=> Correct JVM Architecture Detection

worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/parser/mask/BlocksMaskParser.java
**Fixes #405**
This fixes the issue where masks other than SimpleBlock masks (like Offset mask or negate mask) would not work.
The issue was caused by parseFromListInput() who would throw SuggestInputParseException if the input was not a valid block definition.
But as the parser was catching NoMatchException only, this was causing an error and the MaskFactory was broken.
(The code is very complex, and couldn't test every possible interactions. I assume the more global catch could be problematic, but I don't find any scenario for this.)
=> Fix special masks issue

worldedit-bukkit/src/main/java/com/boydti/fawe/bukkit/adapter/mc1_14/BukkitGetBlocks_1_14.java, worldedit-bukkit/src/main/java/com/boydti/fawe/bukkit/adapter/mc1_15/BukkitGetBlocks_1_15.java, worldedit-bukkit/src/main/java/com/boydti/fawe/bukkit/adapter/mc1_15_2/BukkitGetBlocks_1_15_2.java
This now makes sure to correctly remove the tile entities in the chunk. The old code did nothing at all and would replace the title entity block without removing the tile entity itself.
**Fixes #415** (probably)
The tile entity is removed properly ~~and the chunk is marked as dirty~~.
=> Properly remove tile entities in BukkitGetBlocks_1_15_2

worldedit-bukkit/src/main/java/com/boydti/fawe/bukkit/adapter/mc1_14/BlockMaterial_1_14.java, worldedit-bukkit/src/main/java/com/boydti/fawe/bukkit/adapter/mc1_15/BlockMaterial_1_15.java, worldedit-bukkit/src/main/java/com/boydti/fawe/bukkit/adapter/mc1_15_2/BlockMaterial_1_15_2.java
**Fixes #423 ** and probably other issues as well 
isTranslucent checks for "hasCollision", but has to be negated to make sense (translucent blocks have no collision)
=> Negate "hasCollission" for isTranslucent()

worldedit-core/src/main/java/com/sk89q/util/StringUtil.java, worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/BlockFactory.java, worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/PatternFactory.java, worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/parser/RichParser.java, worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/parser/pattern/RandomPatternParser.java, worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/parser/pattern/SimplexPatternParser.java, worldedit-core/src/main/java/com/sk89q/worldedit/function/pattern/RandomPattern.java
Would partly cover #437 (the simplex mask isn't included)
I've added a SimplexPatternParser which parses `#simplex[scale][pattern]`.
As FAWE has multiple patterns/masks that require additional arguments (provided in [] normally), I've added the class `RichParser` which allows to easily parse those arguments.  Other parsers can extend it, they only need to provide the name of the pattern or mask. They then need to implement the following methods:
(maybe that should be optional) For suggestions of the argument at the given index (e.g. for the simplex pattern, it will suggest numbers as first (index 0) argument and patterns as second (index 1) argument.
Parses the actual pattern or mask with the given arguments. The arguments can be validated there.
That way, the parsers don't need to handle …
=> Start reimplementation of simplex pattern

worldedit-bukkit/src/main/java/com/boydti/fawe/bukkit/FaweBukkit.java
Currently FAWE implements Vault in a way, that even while having Vault as a Softdepent it gets loaded after FAWE, causing permission problems. I don't know why we do that, that's why I changed it to be loaded at the end. This is somewhat related to #529 in that right now Vault can't even work correctly with FAWE, but the issue in #529 is a bit more complex then that.
=> setup vault after loading

worldedit-core/src/main/java/com/sk89q/worldedit/command/argument/AbstractDirectionConverter.java
Fixes issues with expand etc. not working when not specifying a direction. 
Now you are able to look at the direction you want to use again.
Issue was introduced in 28767d6e0fe8779b2f95f3580e5a8388b465d18d
=> Fix convert function in AbstractDirectionConverter

worldedit-core/src/main/java/com/boydti/fawe/object/brush/ErodeBrush.java, worldedit-core/src/main/java/com/boydti/fawe/object/brush/RaiseBrush.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/BrushCommands.java
**Fixes #559 **
Fixes the erosion and pull brushes ArrayIndexOutOfBoundsException, as well as revert their default values to their proper, respective values. Also, re-enabled the ability to edit the arguments ingame for the pull brush.
=> Fix erosion and pull brushes

worldedit-core/src/main/java/com/boydti/fawe/object/extent/SupplyingExtent.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/argument/FactoryConverter.java
**Fixes #612 #501**
Before, RequestExtent caused several problems as Requests are based on ThreadLocals. Those weren't accessible to FAWE after splitting up work into multiple threads. Removing/skipping the RequestExtent would cause issues with world changes for masks and patterns.
This change requests the player's world on each action so it actually uses the correct world when checking masks but also is visible to all threads.
I don't know if this is the proper approach to resolve the linked issues but it works fine from my testings. I didn't spend that much time on it, so feel free to add changes to this PR to improve it or propose a better solution (or a better name for the extent).
=> Implement SupplyingExtent

worldedit-core/src/main/java/com/sk89q/worldedit/LocalSession.java
I believe this may be the issue causing thread locks when wrapping new players. If we're attempting to run a synchronised method within the LocalSesison when initialising it, it may go wrong..?
Opinions?
Relevant parts of stacktrace:
```
[18:59:48] [Paper Watchdog Thread/ERROR]: Current Thread: Server thread
[18:59:48] [Paper Watchdog Thread/ERROR]: 	PID: 23 | Suspended: false | Native: false | State: BLOCKED
[18:59:48] [Paper Watchdog Thread/ERROR]: 	Stack:
[18:59:48] [Paper Watchdog Thread/ERROR]: 		com.sk89q.worldedit.bukkit.WorldEditPlugin.wrapPlayer(WorldEditPlugin.java:493)
[18:59:48] [Paper Watchdog Thread/ERROR]: 		com.sk89q.worldedit.bukkit.BukkitAdapter.adapt(BukkitAdapter.java:136)
[18:59:48] [Paper Watchdog Thread/ERROR]: …
```
=> accessing clipboards should not be synchronized to LocalSession

.github/workflows/gradle.yml
Fixes #678
Updated the job to be a matrix build, running on 1.8 and 1.11. The cache keys now reflect these changes, so this build may take a bit longer than others.
=> Run GitHub Actions build on Java 1.8 and 1.11

worldedit-core/src/main/java/com/sk89q/worldedit/function/mask/MaskIntersection.java, worldedit-core/src/main/java/com/sk89q/worldedit/function/mask/MaskUnion.java
There's no need to duplicate everything when copying the intersection masks, as the Set and array should be the same.
=> There's no need to duplicate everything when copying the intersection masks, as the Set and array should be the same.

worldedit-core/src/main/java/com/boydti/fawe/object/pattern/BiomeApplyingPattern.java, worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/PatternFactory.java, worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/parser/pattern/BiomePatternParser.java, worldedit-core/src/main/java/com/sk89q/worldedit/registry/NamespacedRegistry.java
**Fixes #635**
This reimplements the biome pattern, means `$<biome>` and `#biome[<biome>]` can be used again like a regular pattern (and therefore in combination with noise patterns like `#simplex`, or even better, `#voronoi`)
=> Reimplement biome pattern

worldedit-core/src/main/java/com/boydti/fawe/object/changeset/AbstractChangeSet.java
**Fixes #562**
Previously, the internal id of the block state was used when copying instead of the ordinal id. As FAWE reads it as ordinal when pasting, this caused wrong blocks being placed.
I'm not sure if this caused other issues before or if it was required to use the internal id elsewhere, but from my testings other commands that might use the AbstractChangeSet still seem to work. I'd be happy if someone else could approve functionality too.
- [] I ensured my changes do not break other parts of the code
=> Fix copypaste brush

worldedit-core/src/main/java/com/boydti/fawe/object/pattern/Linear2DBlockPattern.java, worldedit-core/src/main/java/com/boydti/fawe/object/pattern/Linear3DBlockPattern.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/util/SuggestionHelper.java, worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/PatternFactory.java, worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/parser/RichParser.java, worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/parser/mask/AdjacentMaskParser.java, worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/parser/mask/AngleMaskParser.java, worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/parser/mask/ExtremaMaskParser.java, worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/parser/mask/ROCAngleMaskParser.java, worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/parser/mask/RadiusMaskParser.java, worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/parser/mask/SimplexMaskParser.java, worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/parser/pattern/BufferedPatternParser.java, worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/parser/pattern/ExistingPatternParser.java, worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/parser/pattern/Linear2DPatternParser.java, worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/parser/pattern/Linear3DPatternParser.java, worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/parser/pattern/NoisePatternParser.java, worldedit-core/src/main/resources/lang/strings.json
Also smaller translation improvements and cleanup
**Fixes #643**
This reimplements the patterns `#linear2d[<pattern>]`, `#linear3d[<pattern>]`, `#buffer[<pattern>]`, and `#existing`.
I also cleaned up some common parsing code for patterns and masks.
As an addition, linear2d and linear3d can now be scaled, making them even more powerful. Their aliases are implemented pretty lazy right now, as we're just registering the parser twice with different prefixes.
The `#existing` pattern is covered by the mask of the same name in most cases but can be useful in combination with noise patterns like `#simplex`.
=> Reimplement l2d, l3d, existing and buffer pattern

worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/MaskFactory.java, worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/parser/mask/RichOffsetMaskParser.java
**Partly fixes #637**
This reimplements the #offset mask that takes arbitrary integers as offset (compared to `>` and `<` which only allow masking blocks above and below). 
Syntax: `#offset[<x>][<y>][<z>][<mask>]`
=> Reimplement #offset mask

worldedit-core/src/main/java/com/sk89q/worldedit/command/util/annotation/Confirm.java, worldedit-core/src/main/java/com/sk89q/worldedit/extension/platform/Actor.java, worldedit-core/src/main/java/com/sk89q/worldedit/internal/command/ConfirmHandler.java, worldedit-core/src/main/resources/lang/strings.json
`//confirm` was enqueued, therefore it waited for the previous action (which is waiting for confirmation) to finish.
Also, the `confirm-large` option in config wasn't respected previously.
=> Fix confirm deadlock and confirm permissions/limits

worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/adapter/Regenerator.java, worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/regen/Regen_v1_15_R2.java, worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/regen/Regen_v1_16_R1.java, worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/regen/Regen_v1_16_R2.java, worldedit-core/src/main/java/com/boydti/fawe/wrappers/WorldWrapper.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/RegionCommands.java, worldedit-core/src/main/java/com/sk89q/worldedit/world/RegenOptions.java
This PR implements the ability to regenerate regions with biome specifications.
This allows the user to regenerate a region with whatever biome they specify. To use this, the user would execute "//regen BiomeType", where BiomeType is replaced with the name of the biome they want. For example, selecting a region of ocean and typing "//regen plains" will regenerate the region not with the original ocean biome, but with a seamless plains biome with accurate features (cave generation, tree and other populator placement, etc.).
One current downside of this implementation is that the biome-specific regeneration only works in overworld worlds, so using this in worlds like The End and Nether will simply regenerate the region with original, respective terrain instead of the target biome. This …
=> Implement biome-specific regen

worldedit-core/src/main/java/com/sk89q/worldedit/EditSession.java
Corrected typo where max world height was defined as 265
=> Correct typo from max world height of 265 to 256

worldedit-core/src/main/java/com/boydti/fawe/config/Settings.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/SchematicCommands.java, worldedit-core/src/main/java/com/sk89q/worldedit/util/formatting/component/MessageBox.java
This pull request adds a way to set limits on per-player schematics - adding config options which define the maximum space a player's schematics folder can take up (in kb) as well as the maximum number of schematics a player can have.
If there were to continue to be no limit on schematic size, players could conceivably run a script to save a large clipboard under multiple schematic names and in fill up the server's disk space.
**Fixes https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/742**
I have added some rough but functional logic which ensures that while the config options are set, players must have the required room (filesize & slots) in order to save their schematics.
I have also made some adjustments to what `/schematic list` displays, now also showing the size of each …
=> Schem file limits

worldedit-core/src/main/java/com/sk89q/worldedit/command/SchematicCommands.java
This solves the nullpointer exception players get when listing schematics where the parent directory was not made yet
**Fixes #{issue number}**
fixes #780 
added checks to make sure if array returned by getFiles() is null it is not used
=> NullPointer fix for /schematic list

worldedit-core/src/main/java/com/sk89q/worldedit/function/pattern/RepeatingExtentPattern.java
An extent's content was returned flipped when applied for negative positions, as e.g. `Math.abs(-2) % 3` returns 2 instead of 1 (as 1 + -1 * 3 = -2)
(cherry picked from commit b0cf5dd2bf1b9bcbf1c7efff0fe25de7ee9a2090)
=> Properly repeat extents for negative coordinates

worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/regen/Regen_v1_16_R3.java
**Fixes #896**
This prevents entities from being added to the chunk by returning an empty list instead. This way we can avoid triggering the async catcher. As this only applies for 1.16.5, I ignored older versions. I only tested with paper but it seems to work there. so I'm assuming it'll work on forks and spigot too.
=> Don't add entities to chunk on regen

worldedit-core/src/main/java/com/boydti/fawe/beta/implementation/chunk/ChunkHolder.java
This is basically the main "chunk" class for internal FAWE. Chunk operations should (and are) almost always single-threaded operations, however, under certain circumstances, it is possible for the chunk to be "called" (flushed: written to the world and sent to the player) from a separate thread. This would specifically occur from SingleThreadQueueExtent when there are a lot of chunks being loaded in memory by FAWE (where the chunk would then be submitted to a multi-threaded queue). It would therefore be possible for a thread accessing the chunk to attempt to access it in the middle of the call, which can lead to a number of issues, and it is my opinion that the most frequent of these is the NPE seen during lighting operations, where new chunks can be accessed/loaded very quickly, …
=> Apply a lot of synchronization to ChunkHolder

worldedit-core/src/main/java/com/boydti/fawe/object/changeset/CFIChangeSet.java, worldedit-core/src/main/java/com/boydti/fawe/object/changeset/DiskStorageHistory.java
This PR aims to fix a huge issue with thousands of history files saved on disk.
The same behavior has been copied out to CfiChangeSet, class that used the same behaviour to get the next file id.
**Fixes #887**
Firstly, I tried the suggested fix using ``java.nio`` package, that wasn't successful at all.
Then, I decided to simply cache these heavy values in Maps, and load the first value thanks to the old method, still needed with this implementation.
=> Fix performance issues getting next file ids

worldedit-core/src/main/java/com/sk89q/worldedit/world/block/BlockTypesCache.java
Block properties are not in order like they are in Minecraft and WorldEdit
**Fixes #1052**
Modified the HashMap of BlockTypesCache.propertiesMap to be a LinkedHashMap in order to keep the keys in order
=> Keep order of block properties

.github/workflows/build.yml, build.gradle.kts, buildSrc/src/main/kotlin/PlatformConfig.kt, worldedit-bukkit/build.gradle.kts, worldedit-bukkit/src/main/java/com/boydti/fawe/bukkit/FaweBukkit.java, worldedit-bukkit/src/main/java/com/boydti/fawe/bukkit/util/MinecraftVersion.java, worldedit-bukkit/src/test/java/com/sk89q/util/MinecraftVersionTest.java
Changes to chunksStretched + Unit-Tests now work again 🥳 
First of all, unit tests are now executing properly again. This was due to missing libraries, transient dependencies, whatsoever.
The chunksStretched-Property in FaweBukkit.java checked if the version returned by Bukkit.getVersion() + splitting stuff is 16 or higher. This may work, but breaks on Software where this version is overriden, e.g: https://github.com/gommehdnet/cheetah-1.16 - You will only get an ArrayIndexOutOfBounds and Fawe won't start.
Now the version information is retrieved from the package path (`org.bukkit.craftbukkit.v1_16_R3`) with the possibility to compare the object against other versions for future use.
The functionality is ensured by created unit tests.
=> Fixed unit tests + Version Determination

buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/CommonConfig.kt, buildSrc/src/main/kotlin/LibsConfig.kt, buildSrc/src/main/kotlin/PlatformConfig.kt, gradle/wrapper/gradle-wrapper.properties, worldedit-bukkit/build.gradle.kts, worldedit-core/doctools/build.gradle.kts
Upgrade Gradle from 6.9 to 7.0.2
Updated the plugins and scripts we use to be compatible with Gradle 7.0.x. I only checked to make sure the plugin would compile I did not check if it loads properly. This should also bump the Java requirement to Java 11. 
- [] I tested my changes and approved their functionality
=> Update to Gradle 7.0.2

worldedit-core/src/main/java/com/sk89q/worldedit/LocalSession.java
WorldEdit has only LocalSession#getTool(ItemType) and does not have any overload which matches any of the FAWE method signatures.
Fixes #1398
The original WorldEdit method signature is readded again to avoid hacky workarounds when supporting FAWE and WorldEdit
=> Fix incompatibility between WorldEdit and FAWE for LocalSession#getTool

worldedit-core/src/main/java/com/sk89q/worldedit/LocalSession.java
Fixes #1347
The issue was that changesets can contain extra data, for example, files.
Before the history was simply cleared so these objects may not have been properly deleted.
When the player then tried to run /undo or /redo it would run the ``loadSessionHistoryFromDisk`` method, which would cause the files to be read and their history to be repopulated. 
What I do now is ensure that each changeset is properly deleted when clearing history. I also make sure to run the save method which saves the history negative index, so that it should be reset. (I am not sure if this is 100% necessary)
=> Properly delete ChangeSets on history clear

gradle/libs.versions.toml, worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/PaperweightAdapter.java, worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_17_R1_2/regen/PaperweightRegen.java
This uses exactly the same code as WE for seed replacement.
Fixes #1410 
Previously, FAWE always encoded and decoded the full WorldGenSettings. This is only necessary if a custom seed is given as command argument. And even then, it does not fail on invalid structure feature salts injected by bad server software as the RegistryWriteOps don't encode the structure features this way.
=> fix(regen): Use WE PaperweightAdapter for seed replacement

worldedit-core/src/main/java/com/sk89q/worldedit/entity/Player.java
Fixes #1492 
Clipboard saving is done via the executor provided by WorldEdit. By using this executor to close clipboards, we avoid running into the situation where the thread saving the schematic reads from the clipboard after it was closed by the thread firing the PlayerQuitEvent.
=> fix: delay closing of clipboards on quit

worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_17_R1_2/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_17_R1_2/PaperweightGetBlocks.java, worldedit-bukkit/adapters/adapter-1_18/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R1/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_18/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R1/PaperweightGetBlocks.java, worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/NMSAdapter.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/history/changeset/AbstractChangeSet.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/IBlocks.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/blocks/BitSetBlocks.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/blocks/CharBlocks.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/blocks/CharGetBlocks.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/blocks/CharSetBlocks.java, worldedit-core/src/main/java/com/sk89q/worldedit/world/block/BlockTypesCache.java, worldedit-core/src/main/java/com/sk89q/worldedit/world/block/package-info.java
Also:
- Ensure that reserved is never returned in GET block operations
- "empty" thus doesn't exist in the GET update methods; remove the needless checks
- Allow GET/SET chunks to determine their own default values for non-present blocks/sections
=> Add back statically-set reserved IDs for air blocks only, make it clear they're "reserved"

worldedit-core/src/main/java/com/fastasyncworldedit/core/util/StringMan.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/UtilityCommands.java
This adds a new permission which prevents other player's schematics from being displayed in the /schematic list command by using similar logic to /schematic load.
Resolves #1457 
This first will cause it so players that do not have the ``worldedit.schematic.list.other`` permission will not be able to see any directories that are just UUIDs. These are usually the top-level directory outside of the player's own schematic, so if you typed ``schem list ../`` you could see all of the other player's uuids. This filters them from the list.
Then, I check if there are UUIDs in the filter provided by the player, see SchematicCommands 361 for the logic that I implemented in this case (a regex check). 
Now, I wasn't sure whether to display an error message or to simply "not show them". So, feedback …
=> Add worldedit.schematic.list.other permission and functionality

worldedit-core/src/main/java/com/sk89q/worldedit/command/ToolUtilCommands.java, worldedit-core/src/main/java/com/sk89q/worldedit/extension/platform/PlatformCommandManager.java
Fixes https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/1547
We're adapting the proper functionality here while outsourcing our custom aliases to the registration classes.
Looking over the documentation, `//` is the way to toggle the superpickaxe, not any other command or sub command, hence the change proposed aligns our handling with upstream again, while retaining our aliases.
Before the changes are marked as `Ready for merge`: 
- [] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
=> fix: Unify superpickaxe behavior

worldedit-core/src/main/java/com/sk89q/worldedit/command/ChunkCommands.java, worldedit-core/src/main/java/com/sk89q/worldedit/extension/platform/PlatformCommandManager.java
Fixes https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/1535
At the moment we throw two exceptions for improper command handling, the first time the one in the WorldEdit-like format and right afterwards our red-like format. I removed the WorldEdit-like part to match with our other messages.
=> Deduplicate error messages

worldedit-core/src/main/java/com/fastasyncworldedit/core/history/changeset/AbstractChangeSet.java
Fixes #1600
Problem with the issue is, that the coordinates are not set to the NBTTagCompound, therefor on undo the plugin tries to set the TileEntity at 0;0;0
=> Fix: Add coordinates to tile-entity nbt component for undo

worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/DiskOptimizedClipboard.java
The length and therefore limit of the MappedByteBuffer was set using the file size of the entry in the file system. That way, creating new clipboard fails as the file size is 0, and therefor the MappedByteBuffer can't be filled with data as the MappedByteBuffers' limit is 0 as well. 
To get the correct size for the MappedByteBuffer, now the RandomAccessFile#getLength() is used, as the value is set based on the dimensions of the clipboard / region:
https://github.com/IntellectualSites/FastAsyncWorldEdit/blob/main/worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/DiskOptimizedClipboard.java#L119
https://github.com/IntellectualSites/FastAsyncWorldEdit/blob/main/worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/DiskOptimizedClipboard.java#L137 …
=> Fix: Set size of MappedByteBuffer accordingly if no file system entry is present

worldedit-core/src/main/java/com/fastasyncworldedit/core/math/heightmap/HeightMap.java
=> Don't allow heightmap-based brushes to edit the entire world "depth"

worldedit-bukkit/adapters/adapter-1_18_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R2/PaperweightGetBlocks.java, worldedit-bukkit/adapters/adapter-1_18_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R2/PaperweightGetBlocks_Copy.java, worldedit-bukkit/adapters/adapter-1_18_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R2/PaperweightPlatformAdapter.java
Fixes https://discord.com/channels/268444645527126017/344128526435221505/950410113687105606
`//regen -b` now works again, as the data type for the biome was casted wrong.
=> Fix `//regen -b` on 1.18.2

worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/parser/pattern/RandomPatternParser.java
Merge RandomPatternParser#getSuggestions with upstream (https://github.com/EngineHub/WorldEdit/commit/da3fd6c9fa2a185f25312aeac29c48436cd20d14)
Fixes #1509
Removed implementation introduced in https://github.com/IntellectualSites/FastAsyncWorldEdit/commit/ef61ecccaab13481aaa9e6c305c200980d098387 and merged https://github.com/EngineHub/WorldEdit/commit/da3fd6c9fa2a185f25312aeac29c48436cd20d14 into the RandomPatternParser (except the split part) - Does the same thing but works with multiple pattern.
=> Fix tabcomplete for random pattern / multiple pattern

worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_17_R1_2/PaperweightGetBlocks.java, worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_17_R1_2/PaperweightPlatformAdapter.java, worldedit-bukkit/adapters/adapter-1_18/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R1/PaperweightGetBlocks.java, worldedit-bukkit/adapters/adapter-1_18/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R1/PaperweightPlatformAdapter.java, worldedit-bukkit/adapters/adapter-1_18_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R2/PaperweightGetBlocks.java, worldedit-bukkit/adapters/adapter-1_18_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R2/PaperweightPlatformAdapter.java
On Paper, we can avoid the usage of Unsafe as the lock/threading detector is unused there.
As we're synchronizing on the semaphore, we now have a thread local to make it work smoothly on both spigot and paper.
=> Avoid Unsafe on paper

worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/FaweBukkit.java
- Removed the variable 'listeningImages' from 'FaweBukkit.java' due to it not being used anywhere.
The variable 'listeningImages' is never used anywhere in the code and should therefore be removed.
=> refactor: removed unused variable

worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/BukkitPermissionAttachmentManager.java
Fixes a memory leak that attaches and caches PermissionAttachments to NPCs. Citizens uses version 2 UUIDs, which are not used for regular player uuids. Those v2 uuids are now excluded.
=> Fix memory leak by Citizen NPCs

worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/mask/RichMaskParser.java
Fixes #1532
Applies the logic from the RichPatternParser to the RichMaskParser for block tags / categories as well.
The BlockCategoryMask now works again (e.g. `//replace #wool air`)
=> Fix Invalid pattern replacement / block category mask

worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/util/WorldUnloadedException.java, worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/BukkitWorld.java, worldedit-cli/src/main/java/com/sk89q/worldedit/cli/schematic/ClipboardWorld.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/wrappers/WorldWrapper.java, worldedit-core/src/main/java/com/sk89q/worldedit/LocalSession.java, worldedit-core/src/main/java/com/sk89q/worldedit/world/NullWorld.java, worldedit-core/src/main/java/com/sk89q/worldedit/world/World.java, worldedit-core/src/main/resources/lang/strings.json
=> Implement getNameUnsafe method to allow an unloaded world's name to be accessed

worldedit-core/src/main/java/com/sk89q/worldedit/entity/Player.java
=> Don't initialise a DiskOptimisedClipboard before checking for an existing one in the LocalSession when using loadClipboardFromDisk

worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/WorldEditListener.java, worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/WorldEditPlugin.java
- If plugins do silly things like teleport, deop (anything that requires a perm-recheck) (anything that ultimately requires a BukkitPlayer at some point) then the retention of metadata by the server (as it's stored based on a string value indescriminate of player a player relogging) means that a BukkitPlayer caching an old player object will be kept, cached and retrieved by FAWE. Adding a simple memory-based equality check when the player rejoins, and then "invaliding" (redoing) the cache if the players are not equal, fixes this.
- Fixes #1730
=> Check cached bukkit player is the same as the current player online

worldedit-core/src/main/java/com/sk89q/worldedit/command/SchematicCommands.java
Based on the Javadocs of Throwable#getMessage:
> /**
* Returns the detail message string of this throwable.
*
* @\return  the detail message string of this {@\code Throwable} instance
*          (which may be {@\code null}).
*/
the return value of getMessage may be null.
Calling TextComponent.of with a null object throws an error. Rather embed "null"
For further reference: https://discord.com/channels/268444645527126017/344128526435221505/975119810172174336
=> Don't error when loading a schematic fails

worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/NMSAdapter.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/Fawe.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/concurrent/ReentrantWrappedStampedLock.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/configuration/Settings.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/blocks/CharBlocks.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/blocks/CharGetBlocks.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/blocks/CharSetBlocks.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/chunk/ChunkHolder.java
- The set array given in NMSAdapter should have get data written to it
- Having target size >= 2* parallel threads allows for adjacent chunks to be loaded with issues
- "empty" chunk section doesn't need to be localised to the chunk and may be static
- Switch to slightly more performant stream method for testing for non-empty sections
- Implement lock into ChunkHolder preventing any modification to occur whilst the edit is being applied to the world (when ChunkHolder is called)
- Fixes #1664
- May fix #1700
=> Some fixes and improvements to internal queuing

worldedit-core/src/main/java/com/sk89q/worldedit/EditSession.java
- default to a depth of "radius"
- Fixes #1667
=> Avoid int overflow when using fillr in negative coords

worldedit-core/src/main/java/com/sk89q/worldedit/command/tool/AreaPickaxe.java
Adds block break effect to area pickaxe.
Adds block break effect to area superpickaxe to match upstream/recursive pickaxe behavior.
I'm not sure what to do here as the commits that were responsible for adding this were reverted on a merge a _while_ back.
Added in: https://github.com/IntellectualSites/FastAsyncWorldEdit/commit/96e56bdd0cbf5d7640fa30984f78c27a084b6d05
Reverted in: https://github.com/IntellectualSites/FastAsyncWorldEdit/commit/66744bfaa4154569176e677ebb71a36470147d8b
- [X ] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [] New public fields and methods are annotated with `@since TODO`.
=> Add block break effect to area pickaxe

worldedit-core/src/main/java/com/fastasyncworldedit/core/util/WEManager.java
I'm not sure why we introduced the logger interface here, it isn't used to diagnose a current open issue, nor does it provide useful information for the end user, therefore we should remove it.
=> chore: Drop WEManager#cancelEditSafe() logger

worldedit-core/src/main/java/com/fastasyncworldedit/core/FaweCache.java, worldedit-core/src/main/java/com/sk89q/worldedit/extent/MaskingExtent.java
- It's possible for a [Chunk/Char]FilterBlock to be used multiple times in the same "tree" of method calls meaning the mutable paramets (particularly index) get increased within a loop, causing AIOOBs and other issues
- This is only possible on the main thread due to the handling of submissions in SingleThreadQueueExtent, as it ensures all operation remains on the main thread to prevent deadlocks
- Therefore safe usage of FilterBlocks requires that main-threaded operation create a new [Chunk/Char]FilterBlock instance each time
- Further fixes #1681
=> Only implement cache to MaskingExtent when off main thread

worldedit-core/src/main/java/com/sk89q/worldedit/world/snapshot/SnapshotRestore.java
=> Only create entities during a restore if they are contained by the region and the editsession's mask

worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/io/ClipboardReader.java
=> Use the correct CuboidRegion constructor to prevent clipboard height being limited when loading schematics

worldedit-core/src/main/java/com/sk89q/worldedit/util/TreeGenerator.java
=> Prevent unhinged tree generation by doing a sanity check on the block below/block of the tree placement

worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/chunk/ChunkHolder.java
- I can see no reason for it having been set to BOTH for either set or get?
=> Set the correct delegate to the ChunkHolder when using get or set in NULL delegate

worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/BukkitWorld.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/wrappers/WorldWrapper.java, worldedit-core/src/main/java/com/sk89q/worldedit/world/AbstractWorld.java, worldedit-core/src/main/java/com/sk89q/worldedit/world/World.java
=> Use Material rather than legacy int/data when specifying block break effect type

worldedit-core/src/main/java/com/fastasyncworldedit/core/command/tool/brush/BlendBall.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/function/mask/CachedMask.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/BrushCommands.java
- Allows for smoothing of terrain under houses, trees, etc.
- Implements #1539
Will raise a PR to documentation shortly
=> Implement a "sensitivity" setting, a mask, and an option to only distinguish air vs blocks to blendball

worldedit-bukkit/adapters/adapter-1_18_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R2/PaperweightPlatformAdapter.java, worldedit-bukkit/adapters/adapter-1_19/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R1/PaperweightPlatformAdapter.java
there is an issue on servers that might have a different type for game event listeners (https://github.com/Bloom-host/Petal/issues/6)
this fix is also good for fawe because its less maintenance of internal code that can change. the generic stuff doesnt matter for reflection
replaces the copy of removeGameEventListener with calling it directly
=> fix: use servers removeGameEventListener instead of reimpl

worldedit-core/src/main/java/com/sk89q/worldedit/command/ClipboardCommands.java, worldedit-core/src/main/java/com/sk89q/worldedit/regions/CuboidRegion.java, worldedit-core/src/main/java/com/sk89q/worldedit/regions/Region.java
Fixes #1907 
Upstreaming a missing commit from 2020 adding the missing methods. The change in ClipboardCommands isn't needed in FAWE but I kept the method for consistency.
=> fix: upstream missing `Region#getBoundingBox()`

worldedit-core/src/main/java/com/sk89q/worldedit/command/UtilityCommands.java
The command is commented out since 2019, given there is no forseeable change anytime soon, we don't need to keep it up as-is.
Fixes https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/1902
=> fix: Lazy fix macro stacktrace

worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/parser/DefaultBlockParser.java, worldedit-core/src/main/java/com/sk89q/worldedit/world/block/BlockTypes.java
When using a FAWE version that doesn't support the server version, FAWE started causing issues and spamming the logs because the LegacyMapper wasn't initialized correctly, and while initializing, the parse method was used, causing another initialization (and so on). While it will still fail to load correctly, it won't spam the logs anymore over and over again.
The parsing logic in BlockTypes should probably removed altogether, but that needs some investigation on what's needed, so using the parser context seems to be a quick and easy solution.
=>  fix: avoid recursive LegacyMapper initialization

worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_17_R1_2/regen/PaperweightRegen.java, worldedit-bukkit/adapters/adapter-1_18_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R2/regen/PaperweightRegen.java, worldedit-bukkit/adapters/adapter-1_19/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R1/regen/PaperweightRegen.java
Fixes #1894
The level data for the main world was used instead of the actual world, leading to wrong regen results in other worlds.
I also brought the 1.17 code in line with the other versions.
I only tested on 1.19.2, but I don't expect it to behave different on previous versions.
=> fix: use proper level data for regen

worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/SaturatePattern.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/util/TextureUtil.java
Fixes #1933 
1. Updated the asset url to the last release
2. Search through item models as well (No idea why, but many block state models are located in models/item)
3. Change BlockType access by using the BlockTypeCache directly - as the used ids are based on the indexes in the values array of BlockTypeCache. No idea if this changes anything, was just more logical to me.
Example for `#saturate[255][0][120][255]`
Based on my quick testing the changes works so far - Should logs and leaves be replaced as well? For me they don't, but I've never worked with that pattern before, so not that sure what the expected outcome is tbh
=> Fix #saturate-Pattern

worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/FaweRegionExtent.java
Fixes https://github.com/IntellectualSites/fastasyncvoxelsniper/issues/195
FAWE handles internally region restrictions through ExditSession. However, FAWE does not override methods correctlty with direct coordinates (x, y, z) in ``FaweRegionExtent``. Thus, the block may be returned without any process of the region restriction extents.
_Example:_
```java
ExtentTraverser<Extent> traverser = new ExtentTraverser<>(editSession.getExtent());
while (traverser != null && traverser.exists()) {
Extent extent = traverser.get();
if (extent instanceof SingleRegionExtent singleRegionExtent) {
System.out.println(singleRegionExtent.getRegions().iterator().next().toString());
// Polished andeside, inside plot.
System.out.println(singleRegionExtent.getBlock(-3938, 64, 1571)); …
```
=> Fix region restrictions with methods non-overriden

.github/workflows/codeql.yml
I've disabled the action some time ago due to issues on GH's end, but these are resolved by now, as confirmed with https://github.com/IntellectualSites-Internal/FastAsyncWorldEdit-CodeQL-action/actions/runs/3200150726/jobs/5226719917
=> chore: Re-enable CodeQL

worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/BukkitPermissionAttachmentManager.java
Fixes #1966
The Noop-PermissibleAttachment is never added to the entity - but rather shared by reference - therefore can't be removed and throws error in certain edge cases (#1966)
=> Don't error when NPC-annotated "entity" leaves the server

worldedit-core/src/main/java/com/fastasyncworldedit/core/database/RollbackDatabase.java
- y is/was already stored as an int
- Fixes #1931
=> fix: Do not cast y to byte in history database

worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/util/MinecraftVersion.java
Paper has a handy (and less hacky) method to get the running minecraft version. The package name variant also fails when running FAWE in an environment where CB isn't relocated into a versioned package.
=> Read minecraft version from paper if available

worldedit-bukkit/adapters/adapter-1_18_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R2/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_18_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R2/PaperweightStarlightRelighter.java, worldedit-bukkit/adapters/adapter-1_19/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R1/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_19/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R1/PaperweightStarlightRelighter.java
Before Tuinity was integrated into Paper, we had to look up the starlight relight method dynamically.
Tuinity was merged during the 1.17.1 time, so I excluded the 1.17 adapter from the changes
=> Clean up starlight usage

worldedit-core/src/main/java/com/fastasyncworldedit/core/util/JoinedCharSequence.java, worldedit-core/src/main/java/com/sk89q/worldedit/world/block/BlockTypes.java, worldedit-core/src/main/java/com/sk89q/worldedit/world/item/ItemTypes.java
JoinedCharSequence was used to avoid String concatenation. However, String concatenation was heavily improved years ago, and String provides may provide faster `hashCode` and `equals` methods, therefore I propose to drop usages of that class. Also, none of the usages are in hot paths, so even slower code might be preferable over such hacky solutions.
=> Remove usages of JoinedCharSequence

worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/LimitExtent.java
- This allowed some edits to continue after a player left the server when they shouldn't
- Possible sort-of fix for #1985
- Possible fix for #1955
- Should fix #1909
=> fix: don't quash a cancellation FaweException in LimitExtent

worldedit-core/src/main/java/com/sk89q/worldedit/WorldEdit.java
Fixes #1872
Just some refactoring of the regex
=> fix regex and remove forbidden windows characters

worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/Linear2DBlockPattern.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/Linear3DBlockPattern.java
Integer division is truncating, so e.g., both `1 / 2` and `-1 / 2` is `0`. However, we want the latter to be `-1` instead. This can be achieved by using `floorDiv`.
=> Linear Patterns require flooring division

worldedit-core/src/main/java/com/fastasyncworldedit/core/registry/state/PropertyKeySet.java
A simple refactoring of PropertyKeySet to make use of pattern matching in instanceof instead of casting.
=> Use Pattern Matching for instanceof in PropertyKeySet

worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/listener/BrushListener.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/command/tool/MovableTool.java
As the `move` method in `MovableTool` has only one implementation unconditionally returning false without doing anything else, we can deprecated the interface for removal.
The PlayerMoveEvent listener also is somewhat expensive, so removing it will help the performance on larger servers.
=> Remove PlayerMoveEvent listener and deprecate MovableTool

worldedit-core/src/main/java/com/fastasyncworldedit/core/history/changeset/FaweStreamChangeSet.java
Fixes #2118
Writing changes was not in sync with reading changes when using mode 1 or 2.
I assume that this code wasn't properly updated when updating to 1.13, but it remained unnoticed as likely no one set store-redo to false ever before.
I tested basic `//undo` operations in mode 1 and mode 2.
(old code <https://github.com/boy0001/FastAsyncWorldedit/blob/a693d23489da13f2a59fe31794abd9c74b4ac352/core/src/main/java/com/boydti/fawe/object/changeset/FaweStreamChangeSet.java#L127-L138>)
=> Fix reading block states in no redo mode

worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/regions/plotsquared/PlotSquaredFeature.java
Fixes #2120 
(FastAsync)WorldEdit uses inclusive heights maximums whereas PlotSquared uses exclusive values. Using the values provided by PlotSquared therefore requires a subtraction by one.
=> Fix FAWE using exclusive build height from PlotSquared

.github/workflows/announce-release-on-discord.yml, .github/workflows/build-pr.yml, .github/workflows/build.yml, .github/workflows/codeql.yml, .github/workflows/release-drafter.yml, .github/workflows/upload-release-assets.yml
GitHub actions are mutable if not pinned, which allow modifications without revision changes. Let's pin external versions to ensure the version specified matches the version GH action pulls.
=> Pin GH actions to SHA to avoid mutable refs

worldedit-core/src/main/java/com/sk89q/worldedit/EditSession.java
Fixes #2087.
The source of the bug was the rounding of coordinates after deform.
It came down to the differences of rounding negative doubles using casts `(int)` and rounding using `Math.floor()`
Example:
```
(int)( 1.8) = 1
(int)(-1.8) = -1
(int)Math.floor( 1.8) = 1
(int)Math.floor(-1.8) = -2
```
Looking at the original WorldEdit implementation, `Math.floor()` calls are present there too. They were missing in FAWE which resulted in the bug. So this PR simply adds them back in.
=> Fix off by one error for negative coordinates when using -r with //deform

worldedit-core/src/main/java/com/fastasyncworldedit/core/internal/io/FaweOutputStream.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/util/MainUtil.java
`BufferedOutputStream` has a fair amount of overhead as it's thread safe. However, we don't require thread safety here, so we can use an alternative implementation from fastutil which performs better. In my tests, the time spent writing history is halved.
=> Use unsynchronized buffered OutputStream for history

build.gradle.kts
Currently FAWE use for run paper 1.19 and a "static" path for get the jar file. In some cases that is not working.
I replaced the old way to get the jar after shadow with a better one that selects in many cases the jar for out of the box running/debugging.
=> Bump run paper to 1.19.3 and replace path with better solution

worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/regions/plotsquared/FaweDelegateRegionManager.java
fixes IntellectualSites/PlotSquared#3985
=> fix: clear above and below plot gen heights if build heights are larger

worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/DiskOptimizedClipboard.java
- close clipboard on instantiation failure
- set canHaveBiomes when loading clipboard from disk (only possible cause I can find for #2151 ..?)
- check file length and give more appropriate error if it exceeds maximum. Fixes #2151 I guess?
- set byteBuffer to null before invoking cleaning. Fixes #1985
=> feat: improvements to clipboard on disk

worldedit-core/src/main/java/com/sk89q/worldedit/command/ToolUtilCommands.java, worldedit-core/src/main/resources/lang/strings.json
=> fix: add null-check for brush in traceMask

worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/regions/plotsquared/PlotSquaredFeature.java
- Fixes IntellectualSites/PlotSquared#3998
=> fix: invalidate cached FaweMask when a plot is unlinked

worldedit-core/src/main/java/com/sk89q/worldedit/extent/transform/BlockTransformExtent.java
-  NBT will be handled appropriately at another point
- Tested 😮
- Fixes #2085
=> fix: Ensure BaseBlock is not returned when a BlockState is wanted in BlockTransformExtent (#2161

worldedit-bukkit/adapters/adapter-1_19_4/build.gradle.kts, worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/PaperweightFaweWorldNativeAccess.java, worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/PaperweightPlatformAdapter.java, worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/regen/PaperweightRegen.java
Fixes #2175
This updates the paper dev bundle for 1.19.4 and addresses the changes to how CraftChunk is used. I also removed a method that was marked as unused which was based on the old CraftChunk#getHandle method.
To avoid unnecessary compatibility issues, we're using a MethodHandle which is selected based on the available methods.
=> Address incompatibilities after CraftChunk changes in spigot

worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_17_R1_2/PaperweightPlatformAdapter.java, worldedit-bukkit/adapters/adapter-1_18_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R2/PaperweightPlatformAdapter.java, worldedit-bukkit/adapters/adapter-1_19/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R1/PaperweightPlatformAdapter.java, worldedit-bukkit/adapters/adapter-1_19_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R2/PaperweightPlatformAdapter.java, worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/PaperweightPlatformAdapter.java
- This isn't necessarily targeting any fix, but I think we should be ensuring a ticket is being added to chunks "access asynchronously", as done by the getChunkAtAsync method
=> chore: add chunk tickets to all chunks accessed

worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/Regenerator.java
Fixes #2178
Plugins might call the regen code synchronously, in which case we still need to make sure worldgen is run on a different thread, as there are events triggered which require to be called asynchronously.
=> Ensure regen step not running on the main thread

worldedit-core/src/main/java/com/sk89q/worldedit/extent/AbstractDelegateExtent.java, worldedit-core/src/test/java/com/fastasyncworldedit/ArchitecturalTest.java
AbstractDelegateExtent is missing methods that should delegate to the target extent. This leads to falling back to default implementations in Extent that typically perform worse than specialized implementations in the actual extents.
As an example, `//distr` performs ~15x faster with this change.
I excluded the enableHistory method from delegating because it might delegate to the implementation in ExtentBatchProcessorHolder, returning a SingleThreadQueueExtent instead of the actual ParallelQueueExtent. I don't know why the implementation is built the way it is, so I think this needs to be investigated separately.
=> Actually delegate in AbstractDelegateExtent

worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/WorldEditPlugin.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/util/annotation/ConfirmHandler.java
Fixes #1994 
Thanks to @GiantTreeLP to help me to identify the issue with the console command sender from fawe/worldedit.
=> Fixes command context for bukkit console command sender

worldedit-core/src/main/java/com/fastasyncworldedit/core/util/collection/SimpleRandomCollection.java
Fixes #2219
SimpleRandomCollection always selected an entry in the range `[0, 1)`. This is wrong however, as it has to scale to `[0, total)`.
This problem likely wasn't discovered before because most uses of the random pattern make use of `FastRandomCollection` instead.
=> Properly scale the random in SimpleRandomCollection

Jenkinsfile
Simplifies the existing logic by relying on env vars, rather of iterating over the tool list.
=> Simplify Java location in Jenkinsfile

worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/listener/ChunkListener.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/configuration/Settings.java
- It's very resource-intensive and probably doesn't work anyway
- Tick limiter should not be enabled by default, it confuses a lot of people with the console logs
=> chore: remove firework-chunk-loading prevention and default tick limiter to false

worldedit-core/src/main/java/com/fastasyncworldedit/core/configuration/Settings.java
- immediately return limit if unlimited (limit combination take the "higher" value)
- add fawe.limit.unlimited permission and it's an intuitive permission to give
=> fix: more intuitive limit permissions

worldedit-core/src/main/java/com/sk89q/worldedit/EditSessionBuilder.java
- Add regionExtent process to the queue (fixes #2227)
- Correctly wrap extents in each other
=> fix: correctly handle creation of extents in EditSessionBuilder

worldedit-core/src/main/java/com/fastasyncworldedit/core/Fawe.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/configuration/Settings.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/math/BlockVector3ChunkMap.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/IChunkSet.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/QueueHandler.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/SingleThreadQueueExtent.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/blocks/CharSetBlocks.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/blocks/ThreadUnsafeCharBlocks.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/chunk/ChunkHolder.java
Create a copy of SET chunk before processing
- Completely nullifies issue of writing to SET between processing submission and processing completion
- Leads to larger memory footprint, but that is acceptable
- Leads to performance improvement in processing as there is no need to perform any multi-threading protection operations
- Fixes #1861
- Fixes #2074 (gonna go ahead and say it does, this is really the only thing I can think of to do with the issue, and it's super rare anyway (never replicated by anyone else))## Overview
- *tack on some changes (increased default/recommended target size)
- *tack on some changes (minor cleanup)
- *tack on some changes (improve a couple of CharSetBlocks methods)
=> fix: Improve edit processing

worldedit-core/src/main/java/com/fastasyncworldedit/core/history/changeset/AbstractChangeSet.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/history/changeset/AbstractDelegateChangeSet.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/history/changeset/FaweStreamChangeSet.java, worldedit-core/src/main/java/com/sk89q/worldedit/extent/AbstractDelegateExtent.java
Previously, write tasks for the history were submitted to the thread pool separately, causing different threads to process the tasks. However, the `processSet` method is synchronized to ensure only one thread at a time actually writes to history.
This results in many threads being blocked and competing for the monitor.
With this change, we collect the tasks in a queue and only process the tasks on one thread instead.
After enqueueing a task, we check if another thread is already processing the queue.
This does not bring immediate performance improvements in form of speed, however it reduces CPU usage due to reduced contention. Additionally, it doesn't take up threads in the thread pool that block most of the time, allowing better performance when working on multiple FAWE actions …
=> Avoid many threads blocking on AbstractChangeSet#processSet

.github/workflows/build-pr.yml
Noticed in https://github.com/IntellectualSites/FastAsyncWorldEdit/pull/2267#issuecomment-1576221266, that PR builds are no longer generated.
This PR restores the behavior.
=> Archive PR artifacts

worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/PaperweightPlatformAdapter.java
Avoids unhelpful stacktraces in the logs when loading adapters.
This should be integrated before copying it over for 1.20.
=> Improve exception handling on adapter loading

worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/regions/TownyFeature.java
Adds support for TrustedResidents in townblocks and towns, Replaces methods which throw exceptions.
Closes #2249 
TrustedResidents are players which have been given specific rights to act as a townblock owner or town owner, as such they would be able to build/destroy in the areas that FAWE would be used.
Also Closes #2249 by doing the following:
- This commit changes the TownyFeature from only affecting blocks between
y level 0 and 150, changing it to support the lower and upper bounds of
the WorldCoord (top to bottom of the world.)
=> Update & Fix TownyFeature support.

worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/ParallelQueueExtent.java
=> fix: don't "double-up" a setblocks if a region is being set

buildSrc/src/main/kotlin/LibsConfig.kt
- Fixes #2283
- Don't bother with the longer version that allows Locales, we don't need that
=> chore: Address kotlin String#capitalize() deprecation

worldedit-core/src/main/java/com/sk89q/worldedit/world/block/BlockType.java
- Deprecate public BlockType constructors
- People really should not be initialising their own block types. This can and most likely will cause issues.
- Fixes #2290
=> fix: add missing BlockType constructor

worldedit-core/src/main/java/com/fastasyncworldedit/core/configuration/Settings.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/processor/EntityInBlockRemovingProcessor.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/processor/ProcessorScope.java, worldedit-core/src/main/java/com/sk89q/worldedit/EditSessionBuilder.java, worldedit-core/src/main/java/com/sk89q/worldedit/function/entity/ExtentEntityCopy.java
- Includes some refactoring to EditSessionBuilder to prevent doubling-up of processors that are also extents
- Better ordering of the EditSessionBuilder process/extent code to match where extents actually end up in the stack
- Fixes #1941
=> feat: implement removal of entities if they would be in a block after the edit

worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/regions/plotsquared/PlotSquaredFeature.java
- Fixes IntellectualSites/PlotSquared#4070
=> fix: correctly invalidate mask after a plot is merged

worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/IBatchProcessor.java
Fixes issue where remaining blocks outside of layer are not removed in restricted areas.
Modifies one if statement to be correctly checking maxLayer value rather than minLayer value
- Not Applicable: New public fields and methods are annotated with `@since TODO`.
=> fix: regions not trimming Y correctly when restricted

worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/QueueHandler.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/util/task/AsyncNotifyKeyedQueue.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/util/task/AsyncNotifyQueue.java, worldedit-core/src/main/java/com/sk89q/worldedit/extension/platform/AbstractNonPlayerActor.java, worldedit-core/src/main/java/com/sk89q/worldedit/extension/platform/AbstractPlayerActor.java
=> Implement async notify queue that submits to a KeyQueuedExecutorService

worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/WorldEditPlugin.java
Stops FAWE from trying to fill in tab completes for commands it doesn't own
Fixes #1912
Adds a check if the command owner for the command is FAWE
```[tasklist]
```
=> fix: Do not tab complete if command not owned by FAWE

worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_17_R1_2/regen/PaperweightRegen.java, worldedit-bukkit/adapters/adapter-1_18_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R2/regen/PaperweightRegen.java, worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/regen/PaperweightRegen.java, worldedit-bukkit/adapters/adapter-1_20/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R1/regen/PaperweightRegen.java, worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/Regenerator.java
This cleans up some
- constant conditions
- unused method parameters
- use of `Long` where `long` can be used
- typos
- duplicated code
```[tasklist]
```
=> Clean up some regen code

worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_17_R1_2/PaperweightPlatformAdapter.java, worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_17_R1_2/regen/PaperweightRegen.java, worldedit-bukkit/adapters/adapter-1_18_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R2/PaperweightPlatformAdapter.java, worldedit-bukkit/adapters/adapter-1_18_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R2/regen/PaperweightRegen.java, worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/PaperweightPlatformAdapter.java, worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/regen/PaperweightRegen.java, worldedit-bukkit/adapters/adapter-1_20/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R1/PaperweightPlatformAdapter.java, worldedit-bukkit/adapters/adapter-1_20/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R1/regen/PaperweightRegen.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/util/ReflectionUtils.java
While reflections got restricted, we can still use them for everything in the unnamed module.
This allows us to get rid of almost all usages of Unsafe.
If Unsafe is ever removed in future Java releases, we are better prepared, using the proper replacements.
```[tasklist]
```
=> Avoid Unsafe usage where possible

worldedit-core/src/main/java/com/fastasyncworldedit/core/configuration/Settings.java
I would like to include the note that the known WorldEdit bypass permission of the block blacklist (`worldedit.anyblock`) is not considered in the FAWE setting `limits.<group>disallowed-blocks`. Since for the user the border between WorldEdit and FAWE is blurred, this is not very clear at this point.
The `worldedit.anyblock` permission is only in use for the blacklist in `worldedit-config.yml`. This makes sense, but should be explicitly mentioned here.
https://github.com/IntellectualSites/FastAsyncWorldEdit/blob/7288393a39e4438731440b2c4e9a4526e123021d/worldedit-core/src/main/java/com/sk89q/worldedit/EditSessionBuilder.java#L591
https://github.com/IntellectualSites/FastAsyncWorldEdit/blob/7288393a39e4438731440b2c4e9a4526e123021d/worldedit-core/src/main/java/com/sk89q/worldedit/extension/fa …
=> Adding note about "worldedit.anyblock" permission

.github/ISSUE_TEMPLATE/bug_report.yml, build.gradle.kts, gradle/libs.versions.toml, settings.gradle.kts, worldedit-bukkit/adapters/adapter-1_20_2/build.gradle.kts, worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_20_R2/PaperweightAdapter.java, worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_20_R2/PaperweightDataConverters.java, worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_20_R2/PaperweightFakePlayer.java, worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_20_R2/PaperweightWorldNativeAccess.java, worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightBlockMaterial.java, worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightFaweWorldNativeAccess.java, worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightGetBlocks.java, worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightGetBlocks_Copy.java, worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightMapChunkUtil.java, worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightPlatformAdapter.java, worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightPostProcessor.java, worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightStarlightRelighter.java, worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightStarlightRelighterFactory.java, worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/nbt/PaperweightLazyCompoundTag.java, worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/regen/PaperweightRegen.java, worldedit-bukkit/build.gradle.kts, worldedit-core/build.gradle.kts
=> Add support for 1.20.2

worldedit-core/src/main/java/com/sk89q/worldedit/regions/selector/CylinderRegionSelector.java, worldedit-core/src/main/java/com/sk89q/worldedit/regions/selector/EllipsoidRegionSelector.java
When you clear (`//sel`) a region it should effectively remove your selection. For all selection types except for Ellipsoid/Sphere & Cylinder this is true, but for these two types it simply sets their radii to 0 and center to 0,0,0 whilst leaving them in a state to pass their `isDefined()` checks.
For the Ellipsoid regions, you can still operate on the cleared region, so `//set 1` will set a 1x1x1 cube of stone at 0,0,0
This fix sets the boolean used to check if the region selection is defined to `false` in the `clear()` method so the user will correctly receieve the "Make a region selection first" error should they try to operate on the region after clearing it.
```[tasklist]
```
=> Fix "cleared" ellipsoid/cylinder regions still passing isDefined check

worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/Regenerator.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/Fawe.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/FaweCache.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/util/task/FaweForkJoinWorkerThreadFactory.java
I noticed that the ForkJoinPool threads always have 0 as the identifier because the name is set before they are started. We can resolve that by just counting threads ourselves. I decided to generally clean up the various namings of threads created by FAWE.
```[tasklist]
```
=> Streamline fawe thread names

worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_17_R1_2/PaperweightGetBlocks.java, worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_17_R1_2/PaperweightGetBlocks_Copy.java, worldedit-bukkit/adapters/adapter-1_18_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R2/PaperweightGetBlocks.java, worldedit-bukkit/adapters/adapter-1_18_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R2/PaperweightGetBlocks_Copy.java, worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/PaperweightGetBlocks.java, worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/PaperweightGetBlocks_Copy.java, worldedit-bukkit/adapters/adapter-1_20/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R1/PaperweightGetBlocks.java, worldedit-bukkit/adapters/adapter-1_20/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R1/PaperweightGetBlocks_Copy.java, worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightGetBlocks.java, worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightGetBlocks_Copy.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/IChunkGet.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/IQueueChunk.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/SingleThreadQueueExtent.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/blocks/CharBlocks.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/blocks/NullChunkGet.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/chunk/ChunkHolder.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/chunk/NullChunk.java
- remove ChunkHolder locking concept as this is no longer needed
- previously we obtained the copy from chunk GET on finalize, meaning the copy could be replaced by a "newer" one (bad)
- work around this issue by introducing concept of "unique" keys to map chunk GET copies to
- correctly handle resetting of various chunk-related classes to actually allow pooling to work
- remove chunks as they are submitted when flushing a SingleThreadQueueExtenting
- Fixes #2459
- Addresses #2448
- Fixes #2388
=> fix: vastly superier handling of queue chunks

worldedit-core/src/main/java/com/sk89q/worldedit/regions/RegionIntersection.java
Fixes #2470
RegionIntersection can *delegate* to `Region#processSet` of one of the regions only if only this region overlaps with the chunk to process.
Otherwise, we need to check if any region contains a block before we can trim it, i.e. delegate to the default implementation of processSet.
```[tasklist]
```
=> Avoid premature trimming in RegionIntersection

worldedit-core/src/main/java/com/sk89q/worldedit/LocalSession.java
=> fix: clear player's history away from main thread if lock locked

worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_17_R1_2/PaperweightStarlightRelighter.java, worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_17_R1_2/PaperweightStarlightRelighterFactory.java, worldedit-bukkit/adapters/adapter-1_18_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R2/PaperweightStarlightRelighter.java, worldedit-bukkit/adapters/adapter-1_18_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R2/PaperweightStarlightRelighterFactory.java, worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/PaperweightStarlightRelighter.java, worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/PaperweightStarlightRelighterFactory.java, worldedit-bukkit/adapters/adapter-1_20/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R1/PaperweightStarlightRelighter.java, worldedit-bukkit/adapters/adapter-1_20/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R1/PaperweightStarlightRelighterFactory.java, worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightStarlightRelighter.java, worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightStarlightRelighterFactory.java, worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/NMSRelighterFactory.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/processor/lighting/NMSRelighter.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/processor/lighting/RelighterFactory.java
We previously used the raw type `IQueueChunk` as type parameter. However, none of the code depends on that specific interface, we can just fall back to the upper bound `IChunk`. This allows to get rid of warnings and suppressions.
```[tasklist]
```
=> Cleanup rawtypes warnings in relighting code

worldedit-core/src/main/java/com/fastasyncworldedit/core/FaweCache.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/configuration/Settings.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/database/DBHandler.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/util/WEManager.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/HistorySubCommands.java
I noticed that we initialize a few objects that are meant to be singletons twice and keep them in memory.
```[tasklist]
```
=> Reduce duplicated singleton objects

worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_17_R1_2/PaperweightStarlightRelighter.java, worldedit-bukkit/adapters/adapter-1_18_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R2/PaperweightStarlightRelighter.java, worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/PaperweightStarlightRelighter.java, worldedit-bukkit/adapters/adapter-1_20/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R1/PaperweightStarlightRelighter.java, worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightStarlightRelighter.java, worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/StarlightRelighter.java
There is a lot of common code in the PaperweightStarlightRelighter classes. We can reduce code duplication by implementing most of it in a common superclass and let the versioned classes only deal with the actually version-specific code.
```[tasklist]
```
=> Reuse starlight relighting code across versions

worldedit-core/src/main/java/com/sk89q/worldedit/command/ClipboardCommands.java
I noticed that `//paste -n` was not working as expected. The reason is the fast path that delegates to the  `//place` implementation, which didn't support the `-n` flag before. By adding support for it there, we can simply fix that bug (and make the supported flags more consistent).
```[tasklist]
```
=> Support -n (select only) in //place

worldedit-core/src/main/java/com/sk89q/worldedit/command/SchematicCommands.java, worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/io/ClipboardFormats.java
`HashMultiMap` has no guarantees about the order of the values for a key. In our case, this leads to SPONGE_SCHEMATIC being first when iterating in `ClipboardFormats.findByExtension(...)`. We want FAST to come before, therefore we should use a `MultiMap` where values are in the order they are registered. This matches the `registeredFormats` list used by `findByFile`.
The change to the command is needed to allow actually enforcing a different schematic format.
```[tasklist]
```
=> Use FastSchematicReader by default

worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_17_R1_2/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_18_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R2/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_20/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R1/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightFaweAdapter.java, worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/FaweAdapter.java
The `generateTree` code is pretty stable, and we currently just copy it from one version to another. We can introduce a common superclass to deal with the version independent parts of the code and only implement the relevant parts in the versioned adapters.
It would be possible to replace more code using MethodHandles, but I don't think this makes things clearer.
There are also more things in those classes that could potentially deduplicated in a similar manner, but I think this is already hard enough to review properly, and the benefit in other methods seems smaller.
```[tasklist]
```
=> Reuse generateTree code across versions

worldedit-bukkit/src/main/resources/plugin.yml, worldedit-core/src/main/java/com/fastasyncworldedit/core/configuration/Settings.java
I have modified the limit permission so that the permission check is more accurate and the wording is more correct. This also makes it easier to assign permissions and disable the limit bypass for admins (especially the block blacklist of WE and FAWE).
- We down't need the `fawe.limit.*` permission as default permission if we have already checks for `fawe.limit.unlimited`.
- It's enough if only the granted permission is checked.
```[tasklist]
```
=> Unify the limit permission

worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/HeightBoundExtent.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/IBatchProcessor.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/IChunk.java, worldedit-core/src/main/java/com/sk89q/worldedit/regions/CuboidRegion.java, worldedit-core/src/main/java/com/sk89q/worldedit/regions/Region.java
=> fix: add chunk loc to tile entity location when trimming

worldedit-core/src/main/java/com/fastasyncworldedit/core/history/change/BlockPositionChange.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/history/change/MutableBlockChange.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/history/change/MutableFullBlockChange.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/history/changeset/FaweStreamChangeSet.java
As a cleanup for v3, I'd like to go from the 3 methods to read a location to one. The current design is flawed; all implementations actually read the whole position in the `readX` method, requiring the methods to be called in the correct order.
By instead only using one method, we can simplify the code and make it less error-prone. It would also be possible to avoid the `byte[]` buffers in future this way.
I also marked some classes I touched as internal. They aren't currently, but I don't think they are useful to other developers at all.
Due to the (theoretically) breaking changes and the low priority, this targets v3.
```[tasklist]
```
=> History: Read change positions at once

worldedit-core/src/main/java/com/fastasyncworldedit/core/command/tool/brush/ErodeBrush.java
There is no existing check to ensure that a setBlock() is within bounds, i.e that it won't try to set an index above the max. 
So currently using the erode/pull brush where the radius extends it above world height causes an error.
Fixes #2380
Adds a simple check to ensure that the relative coords are within the max dimensions for the given clipboard.
```[tasklist]
```
=> Fix out of bounds error for erode and pull brushes

worldedit-core/src/main/java/com/sk89q/worldedit/regions/CylinderRegion.java
`CylinderRegion` had two bugs:
1. The inverseRadius used for multiplication was based on the unadjusted radius. For consistency, it should use the adjusted one.
2. There was a check whether the while y-level is inside the region, which was wrong as it shifted the chunk coords wrongly and it also didn't check all 4 corners, resulting in wrong shapes for larger selections (with the fixed shift).
The changes bring `//sel cyl` + `//set` in line with `//cyl`.
```[tasklist]
```
=> Use actual radius for inverse and adjust inside region check

worldedit-core/src/main/java/com/fastasyncworldedit/core/database/RollbackDatabase.java
Fixes #2555
`ascending` being false caused the query to contain a `player = ?` case, however, this results in an empty result if we don't pass any uuid.
By cleaning up how we build the query, we can simplify the code and fix the issue.
```[tasklist]
```
=> fix rollback database query

worldedit-core/src/main/java/com/fastasyncworldedit/core/util/collection/RandomCollection.java, worldedit-core/src/main/java/com/sk89q/worldedit/function/pattern/RandomPattern.java
Noise patterns like `#simplex` that take a random pattern, but before, the order didn't match the order of how the command was written down. By keeping the insertion order, the order in the command allows controlling how the resulting noise it mapped to patterns.
```[tasklist]
```
=> Maintain insertion order for RandomPattern sub-patterns

worldedit-core/src/main/java/com/sk89q/worldedit/extent/AbstractDelegateExtent.java
Probably shouldn't be doing this
=> fix: do not forcefully direct to x,y,z methods in AbstractDelegateExtent

worldedit-core/src/main/java/com/sk89q/worldedit/internal/expression/Expression.java, worldedit-core/src/main/java/com/sk89q/worldedit/internal/expression/ExpressionEnvironment.java, worldedit-core/src/main/java/com/sk89q/worldedit/regions/shape/WorldEditExpressionEnvironment.java, worldedit-core/src/test/java/com/sk89q/worldedit/internal/expression/BaseExpressionTest.java
Fixes #2616
This Pull Requests sets the WorldEditExpressionEnvironment after an Expression gets cloned to make sure that the Functions class remains its environment after cloning  to not run into a NullPointerException.
When the Expression is cloned, the WorldEditExpressionEnvironment gets cloned as well while making sure that the offset of the environment is not changing during the cloning process.
```[tasklist]
```
=> fix: set and clone Expression Environment after Expression cloning

worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/ParallelQueueExtent.java
While current use of PQE in FAWE is always covered by a check to ensure PARALLEL_THREADS is > 1, a more defensive strategy might make sense. Alternatively to this change, we could assert that PT > 1, but that seems unnecessary.
Tested by manually setting PARALLEL_THREADS to 1 via debugger directly before the Math.min call.
```[tasklist]
```
=> Make sure to process all chunks in PQE even if PARALLEL_THREADS = 1

worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/RichParser.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/mask/RichMaskParser.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/argument/FactoryConverter.java, worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/MaskFactory.java, worldedit-core/src/main/java/com/sk89q/worldedit/internal/registry/AbstractFactory.java, worldedit-core/src/main/java/com/sk89q/worldedit/internal/registry/InputParser.java
Closely mirrors upstream changes in https://github.com/EngineHub/WorldEdit/pull/2236
"This is a refactor to allow access to a ParserContext within the suggestion methods. This is required for any suggestions within the factory parser that are player-specific"
This PR adds context as an option to the getSuggestions() method of parsers.
While no changes to existing Masks or Patterns are present, this change would allow for that to be done in future.
Originally I had gone through and added context to every parser in FAWE, allowing for the new `getSuggestions(String argumentInput, int index, ParserContext context)` method in RichParser to be abstract, replacing the existing method without context. 
However, that would be a breaking change for any addon plugin using rich parsing such as …
=> Allow factory suggestions to have parser context

worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/transform/RandomTransform.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/util/collection/FastRandomCollection.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/util/collection/RandomCollection.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/util/collection/SimpleRandomCollection.java, worldedit-core/src/main/java/com/sk89q/worldedit/function/pattern/RandomPattern.java
Noise-based patterns can benefit from allowing the same pattern multiple times, e.g. `#simplex[10][red_wool,blue_wool,red_wool,green_wool]` maps random values from `[0, 1)` to `[red_wool, blue_wool, red_wool, green_wool]` (`[0, 0.25)` -> `red_wool` and `[0.5, 0.75)` -> `red_wool`), while before, `red_wool` was just added up to have a weight of 2.
Additionally, we move the random instance out of the collection. The collection doesn't actually depend on a (stateful) random, so that's a bit cleaner.
```[tasklist]
```
=> Allow repeated keys in RandomCollection

worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/parser/DefaultBlockParser.java
=> fix: do not error when attempting to parse "|" as a pattern

worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/BukkitWorld.java
The change proposed adds a few missing spaces:
Additionally, I shifted the severity, because error messages have alerted users before, without any need to.
=> Reword tree type message

worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/pattern/Linear2DPatternParser.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/pattern/Linear3DPatternParser.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/Linear2DBlockPattern.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/Linear3DBlockPattern.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/math/random/Linear2DRandom.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/math/random/Linear3DRandom.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/math/random/SimpleRandom.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/util/collection/SimpleRandomCollection.java
Instead of having specific implementations for `#linear2d` and `#linear3d`, we can implement them using `RandomPattern` and specific `SimpleRandom` implementations.
This has the benefit that weighted patters aren't just ignored but allow for more interesting results.
Example: `#linear2d[white_wool,2%light_gray_wool,4%gray_wool,8%black_wool]`
```[tasklist]
```
=> Implement linear patterns using RandomPattern + SimpleRandom

worldedit-core/src/main/java/com/fastasyncworldedit/core/command/tool/brush/HeightBrush.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/util/MainUtil.java
=> fix: better image reading errors

worldedit-bukkit/adapters/adapter-1_20_4/build.gradle.kts, worldedit-bukkit/adapters/adapter-1_20_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R3/PaperweightBlockMaterial.java
Closes https://github.com/IntellectualSites/FastAsyncWorldEdit/pull/2604
Fixes #2607
Tested via #solidspread pattern and #liquid mask. Seems to work.
```[tasklist]
```
=> Update paperweight 1.20.4 - isOpaque does not exist (anymore)

worldedit-core/src/main/java/com/fastasyncworldedit/core/util/gson/ItemTypeAdapter.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/util/gson/RegionSelectorAdapter.java, worldedit-core/src/main/java/com/sk89q/worldedit/LocalSession.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/SelectionCommands.java, worldedit-core/src/main/java/com/sk89q/worldedit/regions/selector/RegionSelectorType.java, worldedit-core/src/main/java/com/sk89q/worldedit/util/gson/GsonUtil.java, worldedit-core/src/main/java/com/sk89q/worldedit/util/gson/RegionSelectorAdapter.java
=> feat: save region selector to session store

worldedit-core/src/main/java/com/sk89q/worldedit/regions/shape/WorldEditExpressionEnvironment.java
Fixes the incorrect method for relative data checks in expressions (queryRel)
Fixes #2643
Current version erroneously uses toWorld instead of toWorldRel, so `queryRel(0,0,0,t,d)` would always return the data of the block at `0,0,0` for `d`, where it should return the data value of whatever block is `0,0,0` offset.
```[tasklist]
```
=> Fix queryRel returning data value for block at absolute coordinates

worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/LinearBlockPattern.java
When running async the `#linear` pattern can increment index above the length of the `patternsArray`.
This tends not to happen on small operations.
```
[14:49:33 ERROR]: [com.fastasyncworldedit.core.queue.implementation.ParallelQueueExtent] Catching
java.lang.ArrayIndexOutOfBoundsException: Index 9 out of bounds for length 3
at com.fastasyncworldedit.core.function.pattern.LinearBlockPattern.apply(LinearBlockPattern.java:37) ~[FastAsyncWorldEdit-Bukkit-2.9.1-SNAPSHOT.jar:?]
at com.sk89q.worldedit.function.pattern.Pattern.applyBlock(Pattern.java:59) ~[FastAsyncWorldEdit-Bukkit-2.9.1-SNAPSHOT.jar:?]
at com.fastasyncworldedit.core.extent.filter.LinkedFilter.applyBlock(LinkedFilter.java:28) ~[FastAsyncWorldEdit-Bukkit-2.9.1-SNAPSHOT.jar:?]
at …
```
=> Fix Linear pattern index incrementing above array length

worldedit-core/src/main/java/com/fastasyncworldedit/core/util/ExtentTraverser.java
Fixes #2485
Fixes #2546
We already discovered this in #2356, but it took me some debugging to figure out that the linked issues are also caused by this bug. There are two `find` methods, and previously, the bound type of the parameter wasn't strict enough to use the method that takes a `Class<U extends Extent>`, but instead the `find(Object)` method was used. This can be fixed by using a sharper bound.
This *can* theoretically cause compile time issues with existing code, but that will mean that the method is used wrongly most likely.
As a bit of background, this caused two `MaskingExtent`s to exist. But the code in https://github.com/IntellectualSites/FastAsyncWorldEdit/blob/2a08ad28a43a3e179c2b78178b27918ffd3c96a3/worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/processor/ …
=> Use correct find class in ExtentTraverser

worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/processor/MultiBatchProcessor.java
This is a little refactoring for how processors are ordered before being called.
```[tasklist]
```
=> Simplify processor ordering

worldedit-cli/src/main/java/com/sk89q/worldedit/cli/package-info.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/argument/package-info.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/package-info.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/util/annotation/package-info.java, worldedit-core/src/main/java/com/sk89q/worldedit/function/operation/package-info.java, worldedit-core/src/main/java/com/sk89q/worldedit/world/block/package-info.java, worldedit-core/src/main/java/com/sk89q/worldedit/world/chunk/package-info.java
Otherwise, the class additions are omitted from the overview.
=> List FAWE class additions in Javadocs

worldedit-core/src/main/java/com/fastasyncworldedit/core/util/MainUtil.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/util/image/ImageUtil.java
The previous PR did not fix imgur heightmaps due to different methods being called.
Moved the fix in another method, so it can be called from multiple places as needed. I hope I've catched all open resources and closed accordingly.
```[tasklist]
```
=> Fix heightmap brush with imgur images

worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/IBukkitAdapter.java
Fixes #2673
Remove usage of deprecated getName on EntityType enum - use code from upstream to be more in line with WE API
I have not tested these changes yet, but see no issue in them either.
```[tasklist]
```
=> Fix error on adapting custom entities / entity types

worldedit-core/src/main/java/com/fastasyncworldedit/core/util/UpdateNotification.java
- SNAPSHOT will usually only be removed if it's a release version
- If others remove SNAPSHOT, then they're probably doing their own stuff, just use this as the "release" check
- fixes #2744
=> fix: improve how we determine if using FAWE from jenkins

worldedit-core/src/main/java/com/fastasyncworldedit/core/util/gson/BaseItemAdapter.java, worldedit-core/src/main/java/com/sk89q/worldedit/LocalSession.java, worldedit-core/src/main/java/com/sk89q/worldedit/blocks/BaseItem.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/SelectionCommands.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/ToolCommands.java, worldedit-core/src/main/java/com/sk89q/worldedit/util/PropertiesConfiguration.java, worldedit-core/src/main/java/com/sk89q/worldedit/util/YAMLConfiguration.java, worldedit-core/src/main/java/com/sk89q/worldedit/util/gson/GsonUtil.java
=> feat: allow NBT on wand items

worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/blocks/CharBlocks.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/blocks/ThreadUnsafeCharBlocks.java
Fixes #2763
Adds missing `- minSectionPosition` in `set` methods. In other methods this subtraction already exists: 
https://github.com/IntellectualSites/FastAsyncWorldEdit/blob/a7e4d19605484b7eb3f2619ea270114be8fa56cf/worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/blocks/ThreadUnsafeCharBlocks.java#L208
```[tasklist]
```
=> fix: normalize layer when setting ordinal to ThreadUnsafeCharBlocks

worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/PaperweightFaweWorldNativeAccess.java, worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/PaperweightGetBlocks.java, worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/PaperweightPlatformAdapter.java, worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/PaperweightStarlightRelighter.java, worldedit-bukkit/adapters/adapter-1_20/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R1/PaperweightFaweWorldNativeAccess.java, worldedit-bukkit/adapters/adapter-1_20/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R1/PaperweightGetBlocks.java, worldedit-bukkit/adapters/adapter-1_20/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R1/PaperweightPlatformAdapter.java, worldedit-bukkit/adapters/adapter-1_20/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R1/PaperweightStarlightRelighter.java, worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightFaweWorldNativeAccess.java, worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightGetBlocks.java, worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightPlatformAdapter.java, worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightStarlightRelighter.java, worldedit-bukkit/adapters/adapter-1_20_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R3/PaperweightFaweWorldNativeAccess.java, worldedit-bukkit/adapters/adapter-1_20_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R3/PaperweightGetBlocks.java, worldedit-bukkit/adapters/adapter-1_20_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R3/PaperweightPlatformAdapter.java, worldedit-bukkit/adapters/adapter-1_20_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R3/PaperweightStarlightRelighter.java, worldedit-bukkit/adapters/adapter-1_20_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R4/PaperweightFaweWorldNativeAccess.java, worldedit-bukkit/adapters/adapter-1_20_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R4/PaperweightGetBlocks.java, worldedit-bukkit/adapters/adapter-1_20_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R4/PaperweightPlatformAdapter.java, worldedit-bukkit/adapters/adapter-1_20_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R4/PaperweightStarlightRelighter.java, worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/BukkitGetBlocks.java, worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/NMSAdapter.java
- synchronise on the chunk GET object (when available)
- kick it off to be run at some point on the main server thread
=> refactor: adjust chunk sending

worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/TransformFactory.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/FaweParser.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/RichParser.java, worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/BlockFactory.java, worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/ItemFactory.java, worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/MaskFactory.java, worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/PatternFactory.java, worldedit-core/src/main/java/com/sk89q/worldedit/internal/registry/AbstractFactory.java
- e.g. `//set "#mask[grass_block&<air][green_concrete][red_concrete]"`
- fixes #1883
=> fix: allow use of quotes to allow spaces to be used as "and"

worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/PaperweightGetBlocks.java, worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/PaperweightPlatformAdapter.java, worldedit-bukkit/adapters/adapter-1_20/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R1/PaperweightGetBlocks.java, worldedit-bukkit/adapters/adapter-1_20/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R1/PaperweightPlatformAdapter.java, worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightGetBlocks.java, worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightPlatformAdapter.java, worldedit-bukkit/adapters/adapter-1_20_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R3/PaperweightGetBlocks.java, worldedit-bukkit/adapters/adapter-1_20_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R3/PaperweightPlatformAdapter.java, worldedit-bukkit/adapters/adapter-1_20_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R4/PaperweightGetBlocks.java, worldedit-bukkit/adapters/adapter-1_20_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R4/PaperweightPlatformAdapter.java
- Removes possibility of writing to the LevelChunkSection biomes PalettedContainer whilst it is being read from the main thread
=> fix: improve biome setting to avoid writing directly to chunk

worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/blocks/CharBlocks.java
- It's theoretically possible for the section FULL to return a null layer due to race condition with a trim operation
- Locally cache result and if null, recover
- I just had the error from #1592 again
- This seems to have stopped the error, but adding logging did not log, so possibly some bigger bytecode changes?
- Oh well
=> fix: recover from trimmed chunk

worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/IQueueExtent.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/ParallelQueueExtent.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/SingleThreadQueueExtent.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/regions/PolyhedralRegion.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/regions/Triangle.java, worldedit-core/src/main/java/com/sk89q/worldedit/extent/MaskingExtent.java, worldedit-core/src/main/java/com/sk89q/worldedit/regions/CuboidRegion.java, worldedit-core/src/main/java/com/sk89q/worldedit/regions/EllipsoidRegion.java, worldedit-core/src/main/java/com/sk89q/worldedit/regions/Region.java
- rename initFilterBlock from init to create
- remove where we now needlessly init filter blocks
- clone regions in PQE to fix Polyhedral
- fixes #2662
- fixes #2579
=> fix: always init ChunkFilterBlock to the chunk

worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/PaperweightGetBlocks.java, worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/PaperweightGetBlocks_Copy.java, worldedit-bukkit/adapters/adapter-1_20/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R1/PaperweightGetBlocks.java, worldedit-bukkit/adapters/adapter-1_20/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R1/PaperweightGetBlocks_Copy.java, worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightGetBlocks.java, worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightGetBlocks_Copy.java, worldedit-bukkit/adapters/adapter-1_20_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R3/PaperweightGetBlocks.java, worldedit-bukkit/adapters/adapter-1_20_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R3/PaperweightGetBlocks_Copy.java, worldedit-bukkit/adapters/adapter-1_20_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R4/PaperweightGetBlocks.java, worldedit-bukkit/adapters/adapter-1_20_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R4/PaperweightGetBlocks_Copy.java
- resizing a paletted container copy alters the original paletted container
- copy is not clone
- fixes #2790
=> fix: create new biome paletted container when writing

worldedit-bukkit/src/main/resources/plugin.yml
If node "fawe.permpack.basic" exist in other platform than bukkit,this minor bug would exist here too,but i lack the knowledge of finding it out.
A really minor fix , so I just ignore all the contributing requirements :)
=> Add worldedit.tool.none to fawe.permpack.basic

worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/MaskFactory.java, worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/PatternFactory.java
Following the updates in https://github.com/IntellectualSites/FastAsyncWorldEdit/pull/2786, usage of Mask/Pattern factory parseFromInput() within a RichParser paser does not work and causes the surrounding parser to error.
This resolves that error.
Fixes #2825
From my limited testing it appears that this line was not returning the correct type https://github.com/IntellectualSites/FastAsyncWorldEdit/blob/561ef4afdd3dd717d1f040b6440af39354d5826f/worldedit-core/src/main/java/com/sk89q/worldedit/internal/registry/AbstractFactory.java#L113C14-L113C73 which seems to line up with the errors seen in #2825.
By explicitely using Mask/Pattern in the parseFromInput method the issue is resolved.
I am unsure if this is the best way to solve the problem, but it seems to work without breaking the new …
=> Fix parseFromInput Method for Masks and Patterns When Called via API

worldedit-core/src/main/java/com/sk89q/worldedit/command/SchematicCommands.java, worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/io/BuiltInClipboardFormat.java, worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/io/ClipboardFormat.java, worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/io/ClipboardFormats.java, worldedit-core/src/main/resources/lang/strings.json
- no longer allow selecting a format specifically because of the generic extension `.schem`
=> fix: improve schematic format selection

worldedit-core/src/main/java/com/fastasyncworldedit/core/command/tool/brush/CopyPastaBrush.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/database/RollbackDatabase.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/history/changeset/AbstractChangeSet.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/history/changeset/AbstractDelegateChangeSet.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/history/changeset/FaweStreamChangeSet.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/util/MainUtil.java, worldedit-core/src/main/java/com/sk89q/worldedit/LocalSession.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/HistorySubCommands.java, worldedit-core/src/main/java/com/sk89q/worldedit/history/changeset/ChangeSet.java
- reset "origin"/relative X/Z when larger than short min/max value so we do not write incorrect positions
- history size can be larger than int max value
- fixes #2583
=> fix: improve FAWE stream history

build.gradle.kts, buildSrc/build.gradle.kts, worldedit-bukkit/adapters/adapter-1_21/build.gradle.kts, worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_21_R1/PaperweightAdapter.java, worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightPlatformAdapter.java
Fixes #2876
Allow the new 1.21.1 dataversion for the 1.21 adapter. EntityList got removed, so I've added reflection calls (I'm actually not even sure if there is a paper jar without the new chunk system - but no idea how forks handle that). Should work - but I haven't tested that (as I don't even know how). 1.21.1 works so far. Haven't explicitly tested 1.21
```[tasklist]
```
=> Support 1.21.1

worldedit-core/src/main/java/com/fastasyncworldedit/core/command/tool/brush/CopyPastaBrush.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/ResizableClipboardBuilder.java
Fixes a bug shared on discord. 
Use copypaste-brush (`//br copypaste`) with a falsy mask (e.g. `//gmask 0`) and select the area via the first click / interact. Output should state, that `0 blocks were copied.`. Attempting to paste with that brush, results in no future actions being possible (potentially depending on the queue type). 
That's due to the `ResizableClipboardBuilder`. As the mask did not match any blocks, no blocks were added to the builder. Therefor, on build the default dimensions are used, which results in the region spanning from XYZ Integer.MAX_VALUE to XYZ Integer.MIN_VALUE. The RegionVisitor - called by the ForwardExtentCopy - attempts to load all chunks in that range via the SingleThreadQueueExtent. 
The fix is simply using an `EmptyClipboard` if nothing was being …
=> Fix: Copy-Paste-Brush with falsy mask

worldedit-core/src/main/java/com/sk89q/worldedit/EditSession.java
Fixes #2897
Determine the appropriate BlockVector3Set implementation by the region (or rather it's size).
Seems to work, as no error is thrown after 30ish seconds anymore (but I haven't waited for the hollow to complete on > 1bil blocks - chunk gen takes ages)
```[tasklist]
```
=> fix: hollow on large areas fails

worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightBlockMaterial.java, worldedit-bukkit/adapters/adapter-1_20_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R3/PaperweightBlockMaterial.java, worldedit-bukkit/adapters/adapter-1_20_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R4/PaperweightBlockMaterial.java, worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightBlockMaterial.java
`isMovementBlocker` is called in the `HeightmapProcessor` for every edited column at least once, so it's kind of a hot method. On newer Spigot versions, the call `Material#isSolid()` however requires a map lookup as it goes through the registry, slowing down the method call unnecessarily. As we already have the NMS block state available, we can just take the shortcut and call the method that is used by Spigot (and by the NMS heightmap calculation) directly.
```[tasklist]
```
=> Avoid map lookup in `isMovementBlocker` calls

worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/regions/GriefDefenderFeature.java
Fixes #2889
No idea if it works, ain't gonna pay 15 euros just for testing
```[tasklist]
```
=> fix(GriefDefender): invalidate mask on claim change

worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/IBatchProcessor.java, worldedit-core/src/test/java/com/fastasyncworldedit/core/queue/IBatchProcessorTest.java
Fixes #2894
trimY now doesn't overflow into unrelated sections anymore, allowing out of bounds editing. Seems to work for me so far - tests are passing. I couldn't find any edge cases or how that might break other existing behavior. 
I'd highly appreciate additional tests by others.
```[tasklist]
```
=> fix: don't process out of bound section while trimming Y sections

worldedit-core/src/main/java/com/fastasyncworldedit/core/util/MainUtil.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/SchematicCommands.java
Fixes #2892
Not completely happy with how it works - but that's just a limitation of the interface itself.
When not specifying the format, it'll be auto detected. Sadly, the interface outputs the command with the `schem` format specified (which now defaults to v3). But I've updated the exception handling to state that, if the schematic fails to load (the EOFException triggered, when loading a v2 schematic with the default `schem` was handled by the IOException block):
As I'd have to download the file either way when checking for the format, it's simply downloaded even if the format is specified. That way it can utilize the reset functionality of the underlying stream for the reader (v3 in particular). The Closer handles the deletion either way - so it shouldn't clog up anything nor be …
=> fix: allow webinterface schematic format to be detected

worldedit-core/src/main/java/com/fastasyncworldedit/core/configuration/Settings.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/history/change/ChangePopulator.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/history/changeset/AbstractChangeSet.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/history/changeset/AbstractDelegateChangeSet.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/history/changeset/ChangeExchangeCoordinator.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/history/changeset/FaweStreamChangeSet.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/history/changeset/NullChangeSet.java, worldedit-core/src/main/java/com/sk89q/worldedit/function/operation/ChangeSetExecutor.java
`//undo` is inherently single-threaded due to the fact that changes are read from input streams. However, we can split the reading work (producer) from the writing work (consumer) so that it only takes the time the slower of those two operations requires. To reduce allocations, FAWE uses mutable changes, which further complicates things as we need to make sure to not write to a change that is yet to be read. Having an exchanger dealing with two arrays makes that simple.
From my testing, this means the slower action is reading from the input streams, actual improvements might heavily depend on hardware (cpu, memory, disk). 
```[tasklist]
```
=> Faster undo operations

worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/regen/PaperweightRegen.java, worldedit-bukkit/adapters/adapter-1_20_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R3/regen/PaperweightRegen.java, worldedit-bukkit/adapters/adapter-1_20_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R4/regen/PaperweightRegen.java, worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_21_R1/PaperweightAdapter.java, worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/regen/PaperweightRegen.java, worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/Regenerator.java
Fixes #2818
Fixes #2861
We can greatly simplify the regeneration logic by relying on the server's chunk system instead of trying to run the generation ourselves. This works well on Paper, and probably good enough on Spigot. Conceptually, the change is similar to how a `//lazycopy` would work, just with the temporary world as a source. I think this is far better in terms of maintainability.
Tested on Paper 1.21(.1), only, but the code should work on older versions too and as there isn't much low-level implementation details, I also expect Spigot to work.
```[tasklist]
```
=> Fix regen on modern versions

build.gradle.kts, buildSrc/src/main/kotlin/CommonJavaConfig.kt, worldedit-core/src/main/java/com/fastasyncworldedit/core/configuration/Settings.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/CountFilter.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/LinkedFilter.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/MaskFilter.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/block/CharFilterBlock.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/internal/simd/SimdSupport.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/internal/simd/VectorizedCharFilterBlock.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/internal/simd/VectorizedFilter.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/internal/simd/VectorizedMask.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/IQueueExtent.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/ParallelQueueExtent.java, worldedit-core/src/main/java/com/sk89q/worldedit/extent/MaskingExtent.java, worldedit-core/src/main/java/com/sk89q/worldedit/function/mask/Mask.java
This is an experimental, internal feature to use the Vector API when enabled. The current implementation is designed to cover basic use cases (i.e. `//gmask` with single blocks, `//set` with single blocks, `//replace` with single blocks). This could be expanded, but as that needs to be done rather careful to not make performance worse, I left it to the very basics for now.
A quick example of running `//replace dirt diamond_block` on a selection of 2048x320x2048:
Before:
Note that the `hasSection` calls take up the same time in both profiles, same for `initLayer`. The difference is in the `filter` call, which results in many additional calls in the none-specialized variant vs pretty much only memory access and vector instructions in the specialized variant. (There might be ways to optimize …
=> Introduce basic support for Vector API

worldedit-core/src/main/java/com/fastasyncworldedit/core/history/changeset/FaweStreamChangeSet.java
Writing using LinBinaryIO isn't what we want. It only allows writing named tags, but that's not what we want. As I also didn't change the reading accordingly, this results in reading arbitrary data.
Reverting this will (again) cause some additional computation/memory overhead but makes history work correctly again.
```[tasklist]
```
=> Revert history writing using LinBinaryIO

worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/LinkedFilter.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/block/ChunkFilterBlock.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/Filter.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/IDelegateFilter.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/IQueueExtent.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/ParallelQueueExtent.java, worldedit-core/src/main/java/com/sk89q/worldedit/regions/Region.java
- Assume that child filters know about their own forks
- fixes #1874
=> fix: adjust linked filter to be left-right and do not link to new forked instances

worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/io/FastSchematicReaderV3.java, worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/io/sponge/SpongeSchematicV3Reader.java
Fixes #2864
- Applies the set origin in v3 schematics when loading using the fast implementation
- Applies upstream fix for WorldEdit v3 reader https://github.com/EngineHub/WorldEdit/commit/cfd9eeabae14a062bb53dd931e4ec9c6e9be89fb
```[tasklist]
```
=> fix: apply origin to sponge v3 schematics

worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightGetBlocks.java, worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightPlatformAdapter.java, worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightStarlightRelighter.java, worldedit-bukkit/adapters/adapter-1_20_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R3/PaperweightGetBlocks.java, worldedit-bukkit/adapters/adapter-1_20_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R3/PaperweightPlatformAdapter.java, worldedit-bukkit/adapters/adapter-1_20_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R3/PaperweightStarlightRelighter.java, worldedit-bukkit/adapters/adapter-1_20_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R4/PaperweightGetBlocks.java, worldedit-bukkit/adapters/adapter-1_20_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R4/PaperweightPlatformAdapter.java, worldedit-bukkit/adapters/adapter-1_20_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R4/PaperweightStarlightRelighter.java, worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightGetBlocks.java, worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightPlatformAdapter.java, worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightStarlightRelighter.java, worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/FaweBukkitWorld.java, worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/NMSAdapter.java, worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/BukkitWorld.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/math/IntPair.java
- ensure levelChunk is loaded before giving to copy GET - this is not necessarily guaranteed to be nonnull if two edits overlap. Whilst not advised, such an easy failure should not occur when two edits collide
- aims to help #2729
=> fix: some improvements to GET chunk writing

worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/LimitExtent.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/StripNBTExtent.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/IBatchProcessor.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/IBlocks.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/util/NbtUtils.java
Fixes #2928
` IBlocks#getEntities()` and `IBlocks#getTiles()` returned mutable collections before #2883, which FAWE depends on when trimming or stripping NBT data. After the change, `getEntities()` still returns a mutable set which does *not* reflect changes to the original set, and `getTiles()` returns an immutable view of the backing map. This leads to exceptions and misbehavior as seen in #2928.
This change does two things:
- Avoid the usage of the deprecated methods in FAWE and use `tiles()` and `entities()` instead, this should also bring performance benefits
- Make `getTiles()` mutable again. This does not work as easy for `getEntities()`, so I just hope no one outside of FAWE uses this method while relying on mutability.
I also noticed that entity NBT stripping was broken, as we …
=> Fix NBT stripping and trimming

worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/parser/DefaultBlockParser.java
Fixes #2944
Not setting the block with its default NBT data results in the (vanilla) client not rendering the blocks properly. We should also probably pull upstream changes in that area at some point, but that didn't look as straightforward as this fix.
```[tasklist]
```
=> Use default nbt when parsing blocks

worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/CountFilter.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/LinkedFilter.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/MaskFilter.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/internal/simd/SimdSupport.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/internal/simd/VectorizedCharFilterBlock.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/internal/simd/VectorizedFilter.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/internal/simd/VectorizedMask.java
The `applyVector` implementation of `CountFilter` just counted the number of lanes it sees, which doesn't match the behavior of the scalar implementation. By passing around a mask for the affected lanes, we can just count those lanes and get the same counts as without vectorization. We can also move some of the blending code to the pattern rather than the mask, which is also clearer I think.
```[tasklist]
```
=> Fix vectorized CountFilter

worldedit-core/src/main/java/com/sk89q/worldedit/EditSession.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/RegionCommands.java, worldedit-core/src/main/resources/lang/strings.json
=> Allow stacking by block units with //stack (#1539)

worldedit-core/src/main/java/com/fastasyncworldedit/core/history/changeset/FaweStreamChangeSet.java
Fixes #2971 
With the coordinated undo, we now reuse `MutableTileChange` and `MutableEntityChange` across `create` and `remove` changes. This however requires us to also adjust the change in that regard. Unconditionally writing the currently expected value is most likely the simplest solution.
This is not a problem for other change types as we don't have the create/remove situation there.
```[tasklist]
```
=> Fix direction changes for //undo

worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_20_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R3/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_20_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R4/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightFaweAdapter.java, worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/FaweAdapter.java
We can reduce some code duplication by moving the fields that don't require a version-dependent type to the superclass.
```[tasklist]
```
=> Deduplicate adapter fields into superclass

worldedit-core/src/main/java/com/fastasyncworldedit/core/registry/state/PropertyKey.java, worldedit-core/src/main/java/com/sk89q/worldedit/world/block/BlockState.java, worldedit-core/src/main/java/com/sk89q/worldedit/world/block/BlockType.java
Fixes #2961
Different block types can share a property with the same name but with different types. In such case, we shouldn't try to apply the property with invalid values.
We could probably also remove the `IllegalArgumentException` and just return the current block state instead in `BlockState#with(PropertyKey,V)`, but that might hide other problems. Thoughts?
```[tasklist]
```
=> Make property changes more robust

gradle/libs.versions.toml, worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/WorldEditPlugin.java, worldedit-bukkit/src/test/java/com/sk89q/wepif/TestOfflinePermissible.java
Fixes #2987
Compile against 1.21 again to avoid bytecode incompatible with version <1.21.3. ~~Also apply an upstream patch and remove now-unneeded code.~~
The upstream patch initially included doesn't support custom biomes pre 1.21.3, so we need to revisit that separately.
```[tasklist]
```
=> Un-break for versions <1.21.3

.github/workflows/announce-release-on-discord.yml, .github/workflows/build-pr.yml, .github/workflows/build.yml, .github/workflows/upload-release-assets.yml, buildSrc/src/main/kotlin/AdapterConfig.kt, buildSrc/src/main/kotlin/PlatformConfig.kt, gradle/libs.versions.toml, worldedit-bukkit/build.gradle.kts, worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/WorldEditPlugin.java, worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/adapter/Refraction.java, worldedit-core/src/main/java/com/sk89q/worldedit/WorldEditManifest.java
Removes the need for remapping on Paper, reducing disk usage and first-start times.
The project now builds two ShadowJars, one for Paper 1.20.5+ only (Mojmapped), and one that will work on Spigot or Paper for all versions (Spigot mapped).
We publish the Spigot jar to Modrinth twice to make sure their version selector picks the right jar for the platform regardless of the Minecraft version.
I've also added a runtime check on startup to notify the user when they have the wrong jar for their platform, tested with:
- Mojmap jar on reobf Paper 1.20.4: throws useful error as expected
- Spigot-mapped jar on mojmap Paper 1.20.4: "This FastAsyncWorldEdit version does not fully support your version of Bukkit" message, same as before this PR. Do we want to add more checks for this or should we just …
=> Build a Mojang mapped jar in addition to the reobf one, publish both to Modrinth with correct metadata

worldedit-core/src/main/java/com/sk89q/worldedit/EditSession.java, worldedit-core/src/main/java/com/sk89q/worldedit/function/block/SnowSimulator.java, worldedit-core/src/main/java/com/sk89q/worldedit/registry/state/AbstractProperty.java, worldedit-core/src/main/java/com/sk89q/worldedit/world/block/BlockState.java, worldedit-core/src/main/java/com/sk89q/worldedit/world/block/BlockType.java
=> fix: correctly check for properties in thaw/snow

worldedit-bukkit/adapters/adapter-1_21_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_3/PaperweightPlatformAdapter.java
Fixes #2989 
The vanilla 1.21.3 client handles full chunk packets in a way that previously empty chunk sections are not rendered. By forcing the client to drop the chunk completely first, we can ensure that the blocks are rendered again. This might cause some higher load for the client, so we should check if this is still a problem once 1.21.4 is released/supported.
```[tasklist]
```
=> Send forget packet to avoid invisible chunk sections

buildSrc/src/main/kotlin/PlatformConfig.kt, worldedit-bukkit/build.gradle.kts, worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/mask/RichMaskParser.java, worldedit-core/src/main/java/com/sk89q/worldedit/EditSession.java, worldedit-core/src/main/java/com/sk89q/worldedit/function/mask/MaskUnion.java, worldedit-core/src/main/java/com/sk89q/worldedit/function/mask/MaskUnion2D.java
Some dependencies as well as 2 WE classes currently aren't in the correct packages. Aligning the packages with what WE ships will improve compatibility.
This might break other plugins directly depending on FAWE, but I consider it a bug fix.
```[tasklist]
```
=> Move some classes to their expected location

worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightBlockMaterial.java, worldedit-bukkit/adapters/adapter-1_20_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R3/PaperweightBlockMaterial.java, worldedit-bukkit/adapters/adapter-1_20_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R4/PaperweightBlockMaterial.java, worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightBlockMaterial.java, worldedit-bukkit/adapters/adapter-1_21_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_3/PaperweightBlockMaterial.java, worldedit-core/src/main/java/com/sk89q/worldedit/EditSession.java, worldedit-core/src/main/java/com/sk89q/worldedit/function/block/SnowSimulator.java
https://github.com/IntellectualSites/FastAsyncWorldEdit/pull/2976 seems to have introduced a regression - which should be fixed now
- Updated #isFullBlock to actually check for the VoxelShape and not the occlusion of the block
- Updated SnowSimulator to make it more readable (hopefully?) and following Minecrafts snow / rain ticking logic closer
```[tasklist]
```
=> Fix //snow

worldedit-core/src/main/java/com/sk89q/worldedit/regions/Region.java
Clamp the min and max y values to the min and max values of the chunk
Adjusted the layer iteration logic in the Region class to use the minimum and maximum Y-values from the chunk. This prevents unnecessary iterations when getMinimumY or getMaximumY returns extreme values, improving performance efficiency.
```[tasklist]
```
=> Optimize layer iteration to prevent performance overhead.

worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightBlockMaterial.java, worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_20_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R3/PaperweightBlockMaterial.java, worldedit-bukkit/adapters/adapter-1_20_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R3/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_20_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R4/PaperweightBlockMaterial.java, worldedit-bukkit/adapters/adapter-1_20_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R4/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightBlockMaterial.java, worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_21_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_3/PaperweightBlockMaterial.java, worldedit-bukkit/adapters/adapter-1_21_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_3/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_21_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_4/PaperweightBlockMaterial.java, worldedit-bukkit/adapters/adapter-1_21_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_4/PaperweightFaweAdapter.java, worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/BukkitBlockMaterial.java
We can deduplicate and simplify some things there.
```[tasklist]
```
=> Reduce code duplication of PaperweightBlockMaterial

worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightPlatformAdapter.java, worldedit-bukkit/adapters/adapter-1_20_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R3/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_20_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R3/PaperweightPlatformAdapter.java, worldedit-bukkit/adapters/adapter-1_20_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R4/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_20_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R4/PaperweightPlatformAdapter.java, worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightPlatformAdapter.java, worldedit-bukkit/adapters/adapter-1_21_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_3/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_21_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_3/PaperweightPlatformAdapter.java, worldedit-bukkit/adapters/adapter-1_21_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_4/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_21_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_4/PaperweightPlatformAdapter.java, worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/CachedBukkitAdapter.java, worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/FaweAdapter.java, worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/NMSAdapter.java, worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/SimpleBukkitAdapter.java
There are a few things we can simplify here:
- The `short[] nonEmptyBlockCount` was always `null`, so we can remove it
- As a consequence, we don't need to calculate non-air block count anymore
- We can use `int[]` instead of `char[]` for the global palette mapping, and use `System.arraycopy` then
- We can extract duplicated code of the two variants into a common method
```[tasklist]
```
=> Simplify NMSAdapter#createPalette methods

worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightGetBlocks.java, worldedit-bukkit/adapters/adapter-1_20_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R3/PaperweightGetBlocks.java, worldedit-bukkit/adapters/adapter-1_20_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R4/PaperweightGetBlocks.java, worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightGetBlocks.java, worldedit-bukkit/adapters/adapter-1_21_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_3/PaperweightGetBlocks.java, worldedit-bukkit/adapters/adapter-1_21_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_4/PaperweightGetBlocks.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/processor/heightmap/HeightmapProcessor.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/IBlocks.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/chunk/ChunkHolder.java
There are two relevant changes:
1. Instead of a two-dimensional boolean array, we can use one byte array and mark specific bits per heightmap type. This reduces memory loads and simplifies the skip logic a bit. The skip bitset is also replaced by a simple counting variable, which also means we can avoid the array equals check.
2. Add a method `hasNonEmptySection` that can return false if the section is present but only contains air. As minecraft already tracks that information, we can use it and avoid unnecessary array comparisons.
In my tests, the time spent in the HeightmapProcessor was 8 times less than before.
```[tasklist]
```
=> Simplify heightmap calculation and avoid loading empty sections

worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/CountFilter.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/LinkedFilter.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/MaskFilter.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/block/CharFilterBlock.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/internal/simd/SimdSupport.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/internal/simd/VectorFacade.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/internal/simd/VectorizedCharFilterBlock.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/internal/simd/VectorizedFilter.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/internal/simd/VectorizedMask.java
Previously, the use of the vector api forced us to load get and set arrays eagerly. This also caused some overhead in e.g. heightmap recalculation because a set array was present even if no changes were applied to a chunk section.
By using a thin wrapper, we can delay loading the data (or load dummy data) to when it is actually needed. This reduces the mentioned overhead.
Performance difference isn't really noticeable from a user's perspective, as the overhead ran pretty much in parallel to the edit itself. Manually inspecting profiles shows that there is less work done though (especially visible when using `//count`). This might be more noticeable on busy servers or servers with only 2-4 cores.
```[tasklist]
```
=> Allow lazy-loading chunk section data when using Vector API

worldedit-core/src/main/java/com/sk89q/worldedit/command/BiomeCommands.java, worldedit-core/src/main/java/com/sk89q/worldedit/extent/Extent.java, worldedit-core/src/main/java/com/sk89q/worldedit/function/RegionMaskingFilter.java, worldedit-core/src/main/java/com/sk89q/worldedit/function/operation/ForwardExtentCopy.java
Fixes #3006
Constructor (and class itself) now matches upstream again. The actual extent was never used, so I don't really see any reason diffing here.
```[tasklist]
```
=> fix: make RegionMaskingFilter upstream compatible again

worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/io/schematic/MinecraftStructure.java, worldedit-core/src/main/java/com/sk89q/jnbt/NBTInputStream.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/SchematicCommands.java, worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/io/BuiltInClipboardFormat.java
Fixes #3028
- Fixes the linked issue
- Migrate to lin-bus from jnbt
- use datafixer if applicable
```[tasklist]
```
=> fix: correctly save block orientations in structure schematics

worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/block/CharFilterBlock.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/util/TextureUtil.java
=> fix: anglecolor

worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/platform/binding/Bindings.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/platform/binding/ProvideBindings.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/preloader/AsyncPreloader.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/BiomeCommands.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/util/annotation/Confirm.java
=> fix: add nullable region confirm enum

worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/SingleThreadQueueExtent.java
Acquiring/releasing the lock in `getOrCreateChunk` takes a fair amount of time, even with no contention involved. By simplifying from two volatile variables to one, we can already have a fast path before the lock, This cuts the time spent in the method in half in my measurements.
One downside is the scenario where many calls  result in `NullChunk.getInstance()` being returned, as we can't check for the coordinates there. If that *is* a problem, it might make sense to just create multiple NullChunk objects with their actual coordinates.
```[tasklist]
```
=> Check for last chunk before acquiring lock

worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightGetBlocks.java, worldedit-bukkit/adapters/adapter-1_20_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R3/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_20_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R3/PaperweightGetBlocks.java, worldedit-bukkit/adapters/adapter-1_20_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R4/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_20_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R4/PaperweightGetBlocks.java, worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightGetBlocks.java, worldedit-bukkit/adapters/adapter-1_21_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_3/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_21_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_3/PaperweightGetBlocks.java, worldedit-bukkit/adapters/adapter-1_21_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_4/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_21_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_4/PaperweightGetBlocks.java, worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/FaweAdapter.java
We can simplify the logic in the update method:
- Avoid filling the array if all of its content is written later anyway
- Move version-independent loops to common supertype
- Use Arrays.fill instead of manual loops where possible
This also helps avoiding going through hard-to-optimize initialization check code every iteration instead of only once before
```[tasklist]
```
=> Simplify and deduplicate PaperweightGetBlocks#update logic

worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/processor/heightmap/HeightMapType.java, worldedit-core/src/main/java/com/sk89q/worldedit/extent/Extent.java, worldedit-core/src/main/java/com/sk89q/worldedit/function/mask/SolidBlockMask.java
`SolidBlockMask` previously went through all block states on construction to find all movement-blocking block states. While that doesn't take much time, it adds up as the mask is used in other places, e.g. on every click with a brush. Precalculating the values only once additionally allows us to use the information in other places where we previously called into NMS code through multiple layers of abstraction to check whether a block blocks movement.
For example operations using an angle mask can benefit from that.
```[tasklist]
```
=> Only compute solid blocks once

worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/AngleColorPattern.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/AverageColorPattern.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/DesaturatePattern.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/SaturatePattern.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/ShadePattern.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/util/CachedTextureUtil.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/util/DelegateTextureUtil.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/util/RandomTextureUtil.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/util/TextureUtil.java
=> fix: fork texture util where required

worldedit-core/src/main/java/com/fastasyncworldedit/core/command/tool/brush/ScatterBrush.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/command/tool/brush/ScatterCommand.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/command/tool/brush/ScatterOverlayBrush.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/command/tool/brush/ShatterBrush.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/command/tool/brush/SplatterBrush.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/command/tool/brush/SurfaceSpline.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/command/tool/sweep/ClipboardSpline.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/function/mask/CachedMask.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/function/mask/SplatterBrushMask.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/BufferedPattern.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/math/BlockVectorSet.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/math/LocalBlockVectorSet.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/util/collection/BlockVector3Set.java, worldedit-core/src/main/java/com/sk89q/worldedit/EditSession.java
There was a/some issue(s) that were due to a local set being used assumptively. The only instances of the local sets being explicitly used should now only be when using chunk coords, or for the floating tree remover
=> fix: use a holder to allow "upgrading" LocalBV3Set to a full fat one

.github/workflows/build-pr.yml, .github/workflows/build.yml
`upload-artifact` v3 is deprecated and makes jobs fail now. So it's time to update it.
```[tasklist]
```
=> Update workflows to use upload-artifact v4

worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightPlatformAdapter.java, worldedit-bukkit/adapters/adapter-1_20_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R3/PaperweightPlatformAdapter.java, worldedit-bukkit/adapters/adapter-1_20_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R4/PaperweightPlatformAdapter.java, worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightPlatformAdapter.java, worldedit-bukkit/adapters/adapter-1_21_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_3/PaperweightPlatformAdapter.java, worldedit-bukkit/adapters/adapter-1_21_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_4/PaperweightPlatformAdapter.java
That code was only needed for 1.19.4, so it's safe to remove it now completely.
```[tasklist]
```
=> Remove outdated CraftChunk#getHandle workaround

worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/BukkitPermissionAttachmentManager.java
Fixes #3025
should "fix" the issue (or rather, suppress the exception if the attachment is not part of the permissible - which is okay as the intention is to remove it either way ig)
```[tasklist]
```
=> fix: try removing attachment and fail silently if not attached

worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/ParallelQueueExtent.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/chunk/ChunkHolder.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/util/task/FaweForkJoinWorkerThreadFactory.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/util/task/FaweThread.java
`ThreadLocal` has some overhead that can be avoided as we're controlling our thread pools ourselves. By just having specific thread types with direct access, we can improve performance of commands that go through the `ParallelQueueExtent#getExtent()` code a lot (i.e. `//copy`). As most time is spent loading chunks there, it's somewhat hard to measure, but the time spent in the `getExtent()` method is reduced by ~90%.
```[tasklist]
```
=> Avoid ThreadLocal lookup in ParallelQueueExtent

worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightPlatformAdapter.java, worldedit-bukkit/adapters/adapter-1_20_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R3/PaperweightPlatformAdapter.java, worldedit-bukkit/adapters/adapter-1_20_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R4/PaperweightPlatformAdapter.java, worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightPlatformAdapter.java, worldedit-bukkit/adapters/adapter-1_21_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_3/PaperweightPlatformAdapter.java, worldedit-bukkit/adapters/adapter-1_21_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_4/PaperweightPlatformAdapter.java, worldedit-core/src/main/java/com/sk89q/worldedit/function/mask/BiomeMask.java, worldedit-core/src/main/java/com/sk89q/worldedit/world/biome/BiomeTypes.java
BiomeMask and biome access generally are rather slow, and a lot of the slowness is caused by inefficient translation and slow contains checks. The adaption from NMS biomes to WE BiomeType can be simplified as we already set the legacy id (= NMS-internal id). The HashSet can be replaced by a boolean array, similar to how BlockMask works.
```[tasklist]
```
=> Improve BiomeMask performance

worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_20_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R3/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_20_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R4/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_21_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_3/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_21_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_4/PaperweightFaweAdapter.java, worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/FaweAdapter.java, worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/IDelegateBukkitImplAdapter.java, worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/BukkitBlockRegistry.java, worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/adapter/BukkitImplAdapter.java, worldedit-core/src/main/java/com/sk89q/worldedit/world/block/BlockTypesCache.java, worldedit-core/src/main/java/com/sk89q/worldedit/world/registry/BlockRegistry.java
The Material in Bukkit is an enum, which is not very flexible. This PR replaces it with Minecraft's built-in block registry to reduce unnecessary checks. Additionally, it changes values() to getAllDefaultBlockStates() to improve readability.
=> feat: Using Block Registry to Replace Iterating Over the Material Enum

worldedit-core/src/main/java/com/sk89q/worldedit/extension/platform/AbstractPlayerActor.java
`//ascend` and `//descend` functionality used a mutable vector, but the vector got modified in another method. This caused the commands to misbehave. Simply reverting to the original WE code fixes that. As this isn't performance critical, using immutable vectors seems to be fine.
```[tasklist]
```
=> Fix mutability issue leading to wrong behavior in //ascend and //descend

worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/block/CharFilterBlock.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/function/mask/ABlockMask.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/function/mask/AngleMask.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/function/mask/CachedMask.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/blocks/CharBlocks.java
`AngleMask` caused unnecessarily slow block lookups due to its access patterns. That can be improved. I'll add some inline comments about specific changes.
```[tasklist]
```
=> Optimize AngleMask

worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_20_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R3/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_20_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R4/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_21_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_3/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_21_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_4/PaperweightFaweAdapter.java
After #3057, FAWE fails to start due to the `CraftBlockData.createData(…)` method only existing on Paper. Spigot and Paper both have a method `CraftBlockData.fromData(…)` that can be used instead to restore Spigot compatibility.
```[tasklist]
```
=> Restore Spigot compatibility

worldedit-core/src/main/java/com/sk89q/worldedit/command/BrushCommands.java
`#clipboard` didn't work in height brushes anymore, as the filename/url check didn't cover it properly. Additionally, using `#clipboard` previously silently went back to the default height map when no region was selected. Reporting the problem to the user is better.
```[tasklist]
```
=> Make #clipboard in height brush work again

worldedit-core/src/main/java/com/fastasyncworldedit/core/internal/simd/VectorFacade.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/internal/simd/VectorizedCharFilterBlock.java
If we only need to filter a range of y levels of a section rather than the full section, the vectorized filters can still be used. In fact, the code for both supported filter variants can be shared.
```[tasklist]
```
=> Support single y level processing using Vector API

worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/io/FastSchematicReaderV3.java
Reader did not put "id" into the entity tag, which failed the data fixer upper.
https://discord.com/channels/268444645527126017/344128526435221505/1340372691328307270
```[tasklist]
```
=> fix: entity fixup in sponge v3 schematics

worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/ApplyTask.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/ParallelQueueExtent.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/QueueHandler.java, worldedit-core/src/main/java/com/sk89q/worldedit/regions/Region.java
`ParallelQueueExtent` deals with distributing work onto multiple threads to speed up edits. In its current implementation, this is achieved by just using the `Region#getChunks().iterator()` as a queue and let all threads pull the next chunk to work on from there. This works well typically, but it has one downside: Different threads work on neighboring chunks. There are multiple reasons this isn't optimal:
- Filters accessing data of surrounding chunks will cause more cache misses in their `STQE`. As currently this also means that one `STQE` will trim the chunk cached/processed by another `STQE`, we do a lot of extra work in such cases.
- Due to how Minecraft generates chunks, processing neighboring chunks on different threads can be slower if both threads wait for the same resources.
By …
=> Locality-aware chunk distribution

worldedit-core/src/main/java/com/sk89q/worldedit/function/operation/ForwardExtentCopy.java
=> fix: account for "wrapped" clipboards when finding IQueueExtent for OncePerChunkExtent

worldedit-core/src/main/java/com/sk89q/worldedit/function/mask/OffsetMask.java
Fixes #3134
ForwardCopyExtent uses a MutableVector3, and our current OffsetMask implementation modifies it. That results in applying the following function (and potentially other masks) to the wrong block.
=> Fix offset mask mutating vector

worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/StarlightRelighter.java
Fixes #3145
We need to make sure chunks bordering a change are relighted too, as light could spread into them. By just enqueuing 3x3 chunks, light is always properly recalculated now.
=> Properly relight surrounding chunks

worldedit-core/src/main/java/com/sk89q/worldedit/function/mask/BlockCategoryMask.java
The test(BV3) method already uses it this way. It performs around 10x better in the test method itself, though overall speedup is rather 1.5x-2x.
=> Improve block category mask performance

worldedit-core/src/main/java/com/sk89q/worldedit/function/pattern/StateApplyingPattern.java
There are multiple things that can be improved about the state applying pattern:
1. Use `BV3#getBlock(Extent)` instead of `Extent#getBlock(BV3)`
2. Avoid costly `computeIfAbsent`. Not only has that method a very high complexity, but the capturing lambda causes an allocation every time
3. Instead of iterating over the entry set of a map, use an array of specialized entry types
Here is a diff showcasing how this change affects the performance of the `applyBlock` method when running `//set ^[snowy=true]` on a selection of 2048x320x2048:
=> Improve state applying pattern performance

.github/workflows/announce-release-on-discord.yml, .github/workflows/upload-release-assets.yml
This pr allow to use the workflow again for publish releases.
=> fix: update Discord announcement workflow to use correct release tag output

worldedit-core/src/main/java/com/sk89q/jnbt/Tag.java, worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/parser/DefaultBlockParser.java
=> feat: add permission to allow default nbt

worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightGetBlocks.java, worldedit-bukkit/adapters/adapter-1_20_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R3/PaperweightGetBlocks.java, worldedit-bukkit/adapters/adapter-1_20_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R4/PaperweightGetBlocks.java, worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightGetBlocks.java, worldedit-bukkit/adapters/adapter-1_21_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_4/PaperweightGetBlocks.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/block/CharFilterBlock.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/blocks/CharBlocks.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/blocks/CharGetBlocks.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/blocks/CharSetBlocks.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/chunk/ChunkHolder.java
- replace with "forced" memory access order to eliminate race conditions between sections and blocks arrays
=> feat: remove char block sections array

worldedit-core/src/main/java/com/sk89q/worldedit/command/SelectionCommands.java, worldedit-core/src/main/resources/lang/strings.json
* Add the trim command
* Fix issues from PR review
* Cleanup usages of deprecated Vector getters
* chore: cleanup translations & memoize mask
---------
Fixes EngineHub/WorldEdit#1629
Adds upstream's `//trim` command.
=> feat: add upstream's trim command (EngineHub/WorldEdit#2278)

worldedit-core/src/main/java/com/sk89q/worldedit/command/SelectionCommands.java
=> chore: improve performance of upstream's trim command

worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/processor/PlacementStateProcessor.java
=> fix: don't return null when slow applyBlock method is called by CoreProtect

worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_20_R2/PaperweightAdapter.java, worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_20_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext.fawe/v1_20_R3/PaperweightAdapter.java, worldedit-bukkit/adapters/adapter-1_20_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R3/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_20_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext.fawe/v1_20_R4/PaperweightAdapter.java, worldedit-bukkit/adapters/adapter-1_20_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R4/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_21_R1/PaperweightAdapter.java, worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_21_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_21_4/PaperweightAdapter.java, worldedit-bukkit/adapters/adapter-1_21_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_4/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_21_5/build.gradle.kts, worldedit-bukkit/adapters/adapter-1_21_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_21_5/PaperweightAdapter.java, worldedit-bukkit/adapters/adapter-1_21_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_5/PaperweightFaweAdapter.java, worldedit-bukkit/src/main/java/com/sk89q/worldedit/util/formatting/text/adapter/bukkit/SpigotAdapter.java, worldedit-bukkit/src/test/java/com/sk89q/wepif/TestOfflinePermissible.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/tool/QueryTool.java, worldedit-core/src/main/java/com/sk89q/worldedit/util/formatting/text/serializer/gson/StyleSerializer.java, worldedit-core/src/main/java/com/sk89q/worldedit/world/biome/BiomeCategories.java, worldedit-core/src/main/java/com/sk89q/worldedit/world/block/BlockCategories.java, worldedit-core/src/main/java/com/sk89q/worldedit/world/block/BlockTypes.java, worldedit-core/src/main/java/com/sk89q/worldedit/world/entity/EntityTypes.java, worldedit-core/src/main/java/com/sk89q/worldedit/world/item/ItemCategories.java, worldedit-core/src/main/java/com/sk89q/worldedit/world/item/ItemTypes.java, worldedit-core/src/main/resources/lang/strings.json
=> chore: upstream merges

worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/NMSAdapter.java
SENDING_CHUNKS stored lock does not equal lock attempted to be unlocked?!
Fixes #3196
=> fix: occasional "SENDING_CHUNKS stored lock does not equal lock attempted to be unlocked"

worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/MultiClipboardHolder.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/function/generator/SchemGen.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/RandomFullClipboardPattern.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/math/transform/MutatingOperationTransformHolder.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/ClipboardCommands.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/SchematicCommands.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/argument/FactoryConverter.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/tool/brush/ClipboardBrush.java, worldedit-core/src/main/java/com/sk89q/worldedit/math/transform/CombinedTransform.java, worldedit-core/src/main/java/com/sk89q/worldedit/math/transform/Transform.java, worldedit-core/src/main/java/com/sk89q/worldedit/session/PasteBuilder.java
- also implement random rotation to schematic loadall
- "mutable" transform allows random rotation of schematics outside of clipboard brush
- fixes #3129
=> feat: implement "mutable" transform holder for random rotations

.github/workflows/build.yml, build.gradle.kts, buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/LibsConfig.kt, buildSrc/src/main/kotlin/PlatformConfig.kt
Follows PlotSquared and updates the Sonatype publishing.
The plugin is quite limited when facing custom setups - it requires the java or java-library plugin to work. That's not really working for the libs - but as the platform setup is basically just specifying a publication, cloning that behavior is not really hard. Only annoying thing is the log messages:
```
> Configure project :worldedit-libs:core
No compatible plugin found in project :worldedit-libs:core for publishing
> Configure project :worldedit-libs:bukkit
No compatible plugin found in project :worldedit-libs:bukkit for publishing
> Configure project :worldedit-libs:cli
No compatible plugin found in project :worldedit-libs:cli for publishing
> Configure project :worldedit-libs:core:ap
No compatible plugin found in project …
```
=> chore: update publishing

worldedit-bukkit/adapters/adapter-1_21_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_21_5/PaperweightAdapter.java, worldedit-bukkit/adapters/adapter-1_21_6/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_21_6/PaperweightAdapter.java
Fixes #3223
For whatever reason we have two methods to convert from lin tags to nms tags in our adapter. The fix (`add` -> `addAndUnwrap`) was added to the fromNative method, but not our super duper custom  fromNative**Lin** method. As it's literally doing the same thing with identical code (though it uses fully qualified imports) I've just delegated to the one upstream contains and uses (and where the fix was added previously).
`fromNativeLin` is used by `PaperweightFaweAdapter#blockEntityToCompound()`, which is used by CharGetBlocks, yada yada...
=> fix: pasting of colored signs

worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/ApplyTask.java, worldedit-core/src/main/java/com/sk89q/worldedit/regions/ConvexPolyhedralRegion.java, worldedit-core/src/main/java/com/sk89q/worldedit/regions/polyhedron/Triangle.java
=> fix: we should just always clone the region in ApplyTask

worldedit-core/src/main/java/com/fastasyncworldedit/core/FaweVersion.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/WorldEditCommands.java
=> fix: correct `/fawe version` version

worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/RichParser.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/pattern/BiomePatternParser.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/transform/RandomTransformParser.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/util/SuggestionHelper.java, worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/parser/DefaultBlockParser.java, worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/parser/mask/BlocksMaskParser.java, worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/parser/mask/NegateMaskParser.java, worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/parser/mask/OffsetMaskParser.java, worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/parser/pattern/RandomPatternParser.java, worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/parser/pattern/RandomStatePatternParser.java, worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/parser/pattern/SingleBlockPatternParser.java, worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/parser/pattern/TypeOrStateApplyingPatternParser.java
Probably should be merged without squashing
=> Address more getSuggestions deprecations

worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/parser/pattern/RandomStatePatternParser.java
This allows  using `*<blockstate>` to be used directly in other patterns that require a `RandomPattern` input, e.g., noise patterns. Example `//set #simplex[5][*snow]`:
RandomStatePattern is basically just a cut-down variant of RandomPattern, there really isn't much reason to use it at all imo.
=> Use RandomPattern instead of RandomStatePattern

buildSrc/src/main/kotlin/CommonConfig.kt, worldedit-bukkit/adapters/adapter-1_21_6/build.gradle.kts
Uses a custom nexus repository, which caches the dev-bundles. Should help with the occasional CI errors. The repository should only be able to serve dev-bundles. 
Unused bundles (not used within the last 28 days) are deleted from the mirror. Otherwise, those are cached indefinitely. Listing for bundles is not possible - that's why renovate still needs to test against paper repo
=> chore/fix: use mirror repository for paper dev-bundles
