build.gradle
Hopefully this fixes the Jenkins build...
=> Update WorldGuard repo to use https

worldedit-bukkit/src/main/java/com/boydti/fawe/bukkit/FaweBukkit.java
See @IronApollo's [message](https://discordapp.com/channels/268444645527126017/394318266987839509/530166238735892480) for further informations.
=> Temporary removal of tab complete listener

favs/src/main/java/com/thevoxelbox/voxelsniper/SnipeData.java, worldedit-core/src/main/java/com/sk89q/worldedit/EditSession.java
Fixes #17, and an annoying typo in SnipeData :)
=> Fixes #17, and an annoying typo in SnipeData :)

worldedit-bukkit/src/main/java/com/boydti/fawe/bukkit/adapter/v1_13_1/Spigot_v1_13_R2.java, worldedit-core/src/main/java/com/boydti/fawe/FaweCache.java, worldedit-core/src/main/java/com/boydti/fawe/jnbt/NBTStreamer.java, worldedit-core/src/main/java/com/sk89q/jnbt/EndTag.java, worldedit-core/src/main/java/com/sk89q/jnbt/NBTInputStream.java, worldedit-forge/src/main/java/com/sk89q/worldedit/forge/NBTConverter.java
This reverts commit 13d2ae20
Why was this changed. I doubt it did much in terms of performance. It's better to stay as close as we can to the worldedit repo.
=> Revert "Make end tag singleton"

worldedit-core/src/main/java/com/sk89q/worldedit/util/Direction.java
This fixes the barrage of `Unknown block:`
=> Fix incorrect casting of CharSequence to String

worldedit-core/src/main/java/com/sk89q/worldedit/command/GenerationCommands.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/UtilityCommands.java
A few commands did not check the max radius specified in the config.
=> Added missing radius checks

worldedit-core/src/main/java/com/sk89q/worldedit/extent/AbstractDelegateExtent.java
=> Fix infinite loop in OutputExtent and PositionTransformExtent

build.gradle, worldedit-bukkit/src/main/java/com/boydti/fawe/bukkit/FaweBukkit.java, worldedit-core/build.gradle, worldedit-core/src/main/java/com/boydti/fawe/logging/LoggingChangeSet.java, worldedit-core/src/main/java/com/boydti/fawe/logging/MutableBlockData.java
Reimplements BlocksHub support in 1.13.2.
=> Update BlocksHub support

worldedit-core/src/main/java/com/sk89q/worldedit/function/mask/SingleBlockStateMask.java
```
griffin@main.bear-nation.net > /home/minecraft/servers/spawn1152/logs > cat latest.log | wc -l
4351451
```
=> Remove debug line

worldedit-core/src/main/java/com/boydti/fawe/util/ReflectionUtils.java
**Fixes #338**
Adds support for OpenJDK 13 OpenJ9.
Tested with OpenJDK 13 OpenJ9, OpenJDK 13 Hotspot and OpenJDK 8 Hotspot.
=> Add support for OpenJ9 13

worldedit-core/src/main/java/com/sk89q/worldedit/EditSession.java
**Fixes #341**
Before this PR, attempting to create cuboid walls would result in nothing happening. This fixes that.
=> Fix cuboid wall creation

worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/BukkitPlayer.java
=> Fixing that the PlayerDropItemEvent was not fired

worldedit-bukkit/src/main/java/com/boydti/fawe/bukkit/adapter/NMSAdapter.java, worldedit-bukkit/src/main/java/com/boydti/fawe/bukkit/adapter/mc1_14/BukkitAdapter_1_14.java, worldedit-bukkit/src/main/java/com/boydti/fawe/bukkit/adapter/mc1_15/BukkitAdapter_1_15.java, worldedit-bukkit/src/main/java/com/boydti/fawe/bukkit/adapter/mc1_15_2/BukkitAdapter_1_15_2.java
PR because it's a sort of thing that might be bad? idk.
=> Fix FAWE killing chunk ticks. Also allow ticking for set blocks.

worldedit-bukkit/src/main/java/com/boydti/fawe/bukkit/adapter/NMSAdapter.java, worldedit-bukkit/src/main/java/com/boydti/fawe/bukkit/adapter/mc1_14/BukkitGetBlocks_1_14.java, worldedit-bukkit/src/main/java/com/boydti/fawe/bukkit/adapter/mc1_15/BukkitGetBlocks_1_15.java, worldedit-bukkit/src/main/java/com/boydti/fawe/bukkit/adapter/mc1_15_2/BukkitGetBlocks_1_15_2.java, worldedit-core/src/main/java/com/boydti/fawe/beta/CombinedBlocks.java, worldedit-core/src/main/java/com/boydti/fawe/beta/IBlocks.java, worldedit-core/src/main/java/com/boydti/fawe/beta/implementation/blocks/BitSetBlocks.java, worldedit-core/src/main/java/com/boydti/fawe/beta/implementation/blocks/CharBlocks.java, worldedit-core/src/main/java/com/boydti/fawe/beta/implementation/blocks/CharGetBlocks.java, worldedit-core/src/main/java/com/boydti/fawe/beta/implementation/blocks/FallbackChunkGet.java, worldedit-core/src/main/java/com/boydti/fawe/beta/implementation/blocks/NullChunkGet.kt, worldedit-core/src/main/java/com/boydti/fawe/beta/implementation/chunk/ChunkHolder.java, worldedit-core/src/main/java/com/boydti/fawe/beta/implementation/chunk/NullChunk.kt, worldedit-core/src/main/java/com/boydti/fawe/beta/implementation/processors/BatchProcessorHolder.java, worldedit-core/src/main/java/com/boydti/fawe/jnbt/anvil/MCAChunk.java, worldedit-core/src/main/java/com/sk89q/worldedit/world/block/BlockTypesCache.java
Does anyone have any issues with his?
=> Trim performance

worldedit-core/src/main/java/com/boydti/fawe/wrappers/LocationMaskedPlayerWrapper.java
=> Correctly implement functions to fix navigation issues

worldedit-core/src/main/java/com/sk89q/worldedit/command/tool/AreaPickaxe.java
=> Compare using BlockType, not Block for AreaPickaxe, fixes #436

worldedit-core/src/main/java/com/sk89q/worldedit/command/tool/RecursivePickaxe.java
**Fixes #436 again**
actually use the recurse function and not just delete everything in range
=> Fix recurse pick

worldedit-bukkit/src/main/java/com/boydti/fawe/bukkit/regions/plotsquared/PlotSquaredFeature.java, worldedit-core/src/main/java/com/boydti/fawe/Fawe.java, worldedit-core/src/main/java/com/boydti/fawe/config/Settings.java, worldedit-core/src/main/java/com/boydti/fawe/util/IncendoPaster.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/WorldEditCommands.java
=> Fix a few links

worldedit-bukkit/src/main/java/com/boydti/fawe/bukkit/wrapper/AsyncWorld.java
**Fixes #{issue number}**
- [] I included all information required in the sections above
- [] I tested my changes and approved their functionality
- [] I ensured my changes do not break other parts of the code
- [] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/FastAsyncWorldEdit/blob/1.16/CONTRIBUTING.md)
=> Fix builds for paper 1.16.2

worldedit-bukkit/build.gradle.kts, worldedit-bukkit/src/main/java/com/boydti/fawe/bukkit/adapter/mc1_16_1/BlockMaterial_1_16_1.java, worldedit-bukkit/src/main/java/com/boydti/fawe/bukkit/adapter/mc1_16_1/BukkitAdapter_1_16_1.java, worldedit-bukkit/src/main/java/com/boydti/fawe/bukkit/adapter/mc1_16_1/BukkitGetBlocks_1_16_1.java, worldedit-bukkit/src/main/java/com/boydti/fawe/bukkit/adapter/mc1_16_1/FAWEWorldNativeAccess_1_16.java, worldedit-bukkit/src/main/java/com/boydti/fawe/bukkit/adapter/mc1_16_1/MapChunkUtil_1_16_1.java, worldedit-bukkit/src/main/java/com/boydti/fawe/bukkit/adapter/mc1_16_1/nbt/LazyCompoundTag_1_16_1.java, worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/WorldEditPlugin.java, worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/FAWE_Spigot_v1_16_R1.java
Reimplement 1.16.1 support, it was removed due to a error in our build server.
=> reimplement 1.16.1 support

worldedit-bukkit/src/main/java/com/boydti/fawe/bukkit/adapter/mc1_16_2/BukkitAdapter_1_16_2.java
Fixes NMS in 1.16.2 regarding chunk updates
=> Fixes NMS on 1.16.2

worldedit-bukkit/src/main/java/com/boydti/fawe/bukkit/adapter/mc1_16_2/BukkitAdapter_1_16_2.java
=> improve performance of chunk updates for 1.16.2

worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/BukkitConfiguration.java, worldedit-core/src/main/java/com/sk89q/worldedit/LocalConfiguration.java
Fix issue with the schematics folder suddenly generating inside the server home instead of plugin home
=> fix filepath in Local Configuration

worldedit-core/src/main/java/com/sk89q/worldedit/world/biome/BiomeTypes.java, worldedit-core/src/main/java/com/sk89q/worldedit/world/block/BlockTypes.java, worldedit-core/src/main/java/com/sk89q/worldedit/world/entity/EntityTypes.java, worldedit-core/src/main/java/com/sk89q/worldedit/world/item/ItemCategories.java, worldedit-core/src/main/java/com/sk89q/worldedit/world/item/ItemTypes.java
(cherry picked from commit da4d70fab5c5e5efe242260b5d09ca273f944c55)
=> Regenerate list classes from MCUtils

worldedit-bukkit/src/main/java/com/boydti/fawe/bukkit/adapter/mc1_16_2/BukkitAdapter_1_16_2.java
Improves performance and fixes issues with PacketPlayOutChunkMap when using Spigot
=> Only send PacketPlayOutChunkMap for chunk updates

.github/workflows/gradle.yml, README.md
Follow up to https://github.com/IntellectualSites/FastAsyncWorldEdit/commit/da96365504241fa4ed99c5f15747318f02e5727b#commitcomment-42101462
=> Update build description

.github/ISSUE_TEMPLATE/bug---issue-report-for-fastasyncworldedit.md, .github/ISSUE_TEMPLATE/config.yml
This updates the issue template & adds a config which disables issue creation without using a template & links our discord server.
=> Update the issue template & add a config

.github/ISSUE_TEMPLATE/bug---issue-report-for-fastasyncworldedit.md, worldedit-core/src/main/java/com/sk89q/worldedit/function/entity/ExtentEntityCopy.java
=> Fix entity rotation

.github/ISSUE_TEMPLATE/bug---issue-report-for-fastasyncworldedit.md, worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/BukkitPlayer.java, worldedit-core/src/main/java/com/sk89q/worldedit/extension/platform/PlayerProxy.java
=> Fix toggle permission

worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/io/BuiltInClipboardFormat.java, worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/io/SchematicReader.java
- Should help avoid #605 (I'm assuming this is the issue)
- Possible issues with the InputStream being closed/pre-read or so? Thoughts:?
=> Attempt to recover from incorrectly-extensioned schematic reads

worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/BukkitPermissionAttachmentManager.java, worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/BukkitPlayer.java, worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/WorldEditPlugin.java
Apparently we introduced some heavy performance issues with our recent changes, this should fix those
=> fix performance issues in BukkitPlayer permission

worldedit-bukkit/src/main/java/com/boydti/fawe/bukkit/FaweBukkit.java, worldedit-bukkit/src/main/java/com/boydti/fawe/bukkit/regions/GriefPreventionFeature.java, worldedit-bukkit/src/main/java/com/boydti/fawe/bukkit/regions/ResidenceFeature.java, worldedit-bukkit/src/main/java/com/boydti/fawe/bukkit/regions/TownyFeature.java, worldedit-bukkit/src/main/java/com/boydti/fawe/bukkit/regions/Worldguard.java, worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/FAWE_Spigot_v1_15_R2.java, worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/FAWE_Spigot_v1_16_R1.java, worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/FAWE_Spigot_v1_16_R2.java, worldedit-core/src/main/java/com/boydti/fawe/Fawe.java, worldedit-core/src/main/java/com/boydti/fawe/FaweCache.java, worldedit-core/src/main/java/com/boydti/fawe/IFawe.java, worldedit-core/src/main/java/com/boydti/fawe/beta/IBatchProcessor.java, worldedit-core/src/main/java/com/boydti/fawe/beta/implementation/blocks/CharBlocks.java, worldedit-core/src/main/java/com/boydti/fawe/configuration/file/YamlConfiguration.java, worldedit-core/src/main/java/com/boydti/fawe/jnbt/anvil/MCAChunk.java, worldedit-core/src/main/java/com/boydti/fawe/jnbt/anvil/MCAFile.java, worldedit-core/src/main/java/com/boydti/fawe/jnbt/streamer/StreamDelegate.java, worldedit-core/src/main/java/com/boydti/fawe/logging/rollback/RollbackOptimizedHistory.java, worldedit-core/src/main/java/com/boydti/fawe/object/brush/InspectBrush.java, worldedit-core/src/main/java/com/boydti/fawe/object/brush/visualization/cfi/HeightMapMCAGenerator.java, worldedit-core/src/main/java/com/boydti/fawe/util/EditSessionBuilder.java, worldedit-core/src/main/java/com/boydti/fawe/util/MainUtil.java, worldedit-core/src/main/java/com/boydti/fawe/util/TextureUtil.java, worldedit-core/src/main/java/com/sk89q/worldedit/extent/transform/BlockTransformExtent.java, worldedit-core/src/main/java/com/sk89q/worldedit/function/mask/MaskIntersection.java, worldedit-core/src/main/java/com/sk89q/worldedit/regions/EllipsoidRegion.java, worldedit-core/src/main/java/com/sk89q/worldedit/world/block/BlockTypesCache.java
This PR removed the `debug()` methods in IFawe.java and Fawe.java and replaces their usages with a proper logger.
It also removes (almost) all usages of System.out or System.err and replaces them with a proper logger.
Some new messages were added for debugging purposes.
=> Better logger support

worldedit-core/src/main/java/com/sk89q/worldedit/extension/platform/PlatformCommandManager.java, worldedit-core/src/main/java/com/sk89q/worldedit/extension/platform/binding/ConsumeBindings.java
fix tabcomplete for biomes and tree types
**Fixes #457**
fix tabcomplete for biomes and tree types
=> fix tabcomplete for biomes and tree types, fixes #457

worldedit-core/src/main/java/com/sk89q/worldedit/function/operation/ForwardExtentCopy.java
**Fixes #701 **
Don't try to copy ComplexEntityParts
=> Don't paste ComplexEntityParts

worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/BukkitPlayer.java
=> Allow nullable BukkitPlayers for whatever reason WorldGuard needs them for I guess?

worldedit-bukkit/src/main/java/com/boydti/fawe/bukkit/adapter/mc1_15_2/BukkitGetBlocks_1_15_2.java, worldedit-bukkit/src/main/java/com/boydti/fawe/bukkit/adapter/mc1_16_1/BukkitGetBlocks_1_16_1.java, worldedit-bukkit/src/main/java/com/boydti/fawe/bukkit/adapter/mc1_16_2/BukkitGetBlocks_1_16_2.java, worldedit-core/src/main/java/com/boydti/fawe/beta/IChunkSet.java, worldedit-core/src/main/java/com/boydti/fawe/beta/implementation/blocks/CharSetBlocks.java, worldedit-core/src/main/java/com/boydti/fawe/beta/implementation/blocks/FallbackChunkGet.java, worldedit-core/src/main/java/com/boydti/fawe/beta/implementation/chunk/ChunkHolder.java, worldedit-core/src/main/java/com/boydti/fawe/jnbt/anvil/MCAChunk.java, worldedit-core/src/main/java/com/boydti/fawe/object/HistoryExtent.java, worldedit-core/src/main/java/com/boydti/fawe/object/NullChangeSet.java, worldedit-core/src/main/java/com/boydti/fawe/object/brush/visualization/VisualExtent.java, worldedit-core/src/main/java/com/boydti/fawe/object/change/MutableBiomeChange.java, worldedit-core/src/main/java/com/boydti/fawe/object/changeset/AbstractChangeSet.java, worldedit-core/src/main/java/com/boydti/fawe/object/changeset/AbstractDelegateChangeSet.java, worldedit-core/src/main/java/com/boydti/fawe/object/changeset/CFIChangeSet.java, worldedit-core/src/main/java/com/boydti/fawe/object/changeset/FaweStreamChangeSet.java, worldedit-core/src/main/java/com/boydti/fawe/object/clipboard/DiskOptimizedClipboard.java, worldedit-core/src/main/java/com/boydti/fawe/object/extent/MultiTransform.java, worldedit-core/src/main/java/com/boydti/fawe/object/extent/OffsetExtent.java, worldedit-core/src/main/java/com/boydti/fawe/object/extent/ProcessedWEExtent.java, worldedit-core/src/main/java/com/boydti/fawe/object/extent/RandomOffsetTransform.java, worldedit-core/src/main/java/com/boydti/fawe/object/extent/ScaleTransform.java, worldedit-core/src/main/java/com/boydti/fawe/object/extent/SelectTransform.java, worldedit-core/src/main/java/com/sk89q/worldedit/extent/MaskingExtent.java, worldedit-core/src/main/java/com/sk89q/worldedit/extent/OutputExtent.java, worldedit-core/src/main/java/com/sk89q/worldedit/extent/PassthroughExtent.java, worldedit-core/src/main/java/com/sk89q/worldedit/extent/world/ChunkLoadingExtent.java, worldedit-core/src/main/java/com/sk89q/worldedit/extent/world/WatchdogTickingExtent.java
Since we're only supporting 1.15+ there's no need to try anything other than compatibility
This will currently break any existing biome history (and biome history only) files.
=> Full support for 3D biomes

worldedit-core/src/main/java/com/boydti/fawe/wrappers/SilentPlayerWrapper.java
=> Added TODO Comment

worldedit-core/src/main/java/com/sk89q/worldedit/function/generator/ForestGenerator.java, worldedit-core/src/main/java/com/sk89q/worldedit/util/TreeGenerator.java
Added crimson and warped fungus tree types
=> Add 1.16 tree types

worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/WorldEditPlugin.java
=> Maybe we should actually load the 1.16.4 adapter as well

worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/FAWE_Spigot_v1_16_R2.java
=> Change Method on 1.16 R2

worldedit-core/src/main/java/com/boydti/fawe/beta/implementation/queue/SingleThreadQueueExtent.java
**Fixes #{issue number}**
- [] I included all information required in the sections above
- [] I tested my changes and approved their functionality
- [] I ensured my changes do not break other parts of the code
- [] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/FastAsyncWorldEdit/blob/1.16/CONTRIBUTING.md)
=> Add more debug output to find a error

worldedit-core/src/main/java/com/sk89q/worldedit/command/tool/LongRangeBuildTool.java
I talked about this issue privately with SirYwell, this is honnestly too critical to explain the issue publically. If you want more details, get in touch with me on Discord ``◀ λųгέłɪεŋ ▶#3642``
_Thanks and sorry for not following a few "standards" :)_
_Discord_
=> Fixes critical issue with LongRangeBuildTool tool

buildSrc/src/main/kotlin/PlatformConfig.kt
https://discord.com/channels/268444645527126017/344128526435221505/829021928483848222
**Fixes #1015**
Fix the Classpath from WorldEdit to FastAsyncWorldEdit
- [] I tested my changes and approved their functionality
- [] I ensured my changes do not break other parts of the code
=> Change truezip classpath to FastAsyncWorldEdit

worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/platform/binding/Bindings.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/platform/binding/ConsumeBindings.java
=> Alter handling of errors in bindings

worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/regions/plotsquaredv4/PlotSquaredFeature.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/configuration/Settings.java
Fixes https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/1372
=> Fix PSv4 config error

contrib/craftscripts/SUBMITTING.md
Change 'FastAsybcWorldEdit' to 'FastAsyncWorldEdit'.
=> typo: spelling mistake of 'FastAsyncWorldEdit'

worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/FaweBukkit.java
Resolves #1428
Replace plugins with a list that is sorted using the compareToIgnoreCase statement. (The plugins command uses the CASE_INSENSITIVE_ORDER comparator, which this method uses this same comparator)
=> Sort plugins on debugpaste

worldedit-bukkit/adapters/adapter-1_17_1/build.gradle.kts, worldedit-core/src/main/java/com/sk89q/worldedit/scripting/MinecraftHidingClassShutter.java, worldedit-core/src/main/java/com/sk89q/worldedit/scripting/RhinoCraftScriptEngine.java, worldedit-core/src/main/java/com/sk89q/worldedit/util/TargetBlock.java
c407471 Re-add class shutter with tweaks. (1947)
29f1c66 If a trace hits the world limit, cancel it (1942)
=> upstream: Update upstream

worldedit-bukkit/adapters/adapter-1_17_1/build.gradle.kts
=> build: Update paperweight

worldedit-core/src/main/java/com/fastasyncworldedit/core/util/TaskManager.java
Fixes the NPE because TaskManager.INSTANCE is never assigned.
obviously.
=> Fix: NPE on access on TaskManager instance

worldedit-core/src/main/java/com/fastasyncworldedit/core/util/WEManager.java
Temporary fixes WEManager initialization:
```
[09:56:10] [Server thread/WARN]: [FastAsyncWorldEdit] Task #11 for FastAsyncWorldEdit v2.0.0-SNAPSHOT-13;7da921e generated an exception
java.lang.NullPointerException: Cannot invoke "com.fastasyncworldedit.core.util.WEManager.addManager(com.fastasyncworldedit.core.regions.FaweMaskManager)" because the return value of "com.fastasyncworldedit.core.util.WEManager.weManager()" is null
at com.fastasyncworldedit.bukkit.FaweBukkit.setupPlotSquared(FaweBukkit.java:314) ~[FastAsyncWorldEdit-Bukkit-2.0.0-SNAPSHOT-13.jar:?]
at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-100]
at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) …
```
=> Fix WEManager

buildSrc/src/main/kotlin/AdapterConfig.kt, buildSrc/src/main/kotlin/CommonConfig.kt, buildSrc/src/main/kotlin/CommonJavaConfig.kt, worldedit-bukkit/adapters/adapter-1_17_1/build.gradle.kts, worldedit-bukkit/adapters/adapter-1_18/build.gradle.kts, worldedit-bukkit/build.gradle.kts
We don't need to hit the central repository more than needed, currently more than thrice time for certain artifacts, when not read from cache.
Let's see if it builds on GH actions too. Works fine in a local environment.
=> ci: Cleanup maven repositories

worldedit-core/src/main/java/com/fastasyncworldedit/core/command/tool/brush/HeightBrush.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/math/heightmap/ArrayHeightMap.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/math/heightmap/FlatScalableHeightMap.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/math/heightmap/HeightMap.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/math/heightmap/ScalableHeightMap.java
=> Heightmaps used for brushes etc. should be normalised to zero.

worldedit-core/src/main/java/com/fastasyncworldedit/core/command/tool/brush/SurfaceSpline.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/function/generator/SchemGen.java
=> Fix surfacespline not working below Y 0

worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/ExtentHeightCacher.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/function/mask/AngleMask.java
=> Fix angle mask not working below Y 0

worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/FaweBukkit.java, worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/util/MinecraftVersion.java, worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/BukkitServerInterface.java, worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/adapter/BukkitImplLoader.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/DiskOptimizedClipboard.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/SimpleClipboard.java, worldedit-core/src/main/java/com/sk89q/worldedit/EditSession.java, worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/Clipboard.java, worldedit-core/src/main/java/com/sk89q/worldedit/regions/CuboidRegion.java
=> Fix clipboards to allow proper heights by allowing extended CuboidRegion heights

worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/WorldEditPlugin.java
=> Load legacy config file before firing PlatformsRegisteredEvent

worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_17_R1_2/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_18/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R1/PaperweightFaweAdapter.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/util/NbtUtils.java, worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/parser/DefaultItemParser.java, worldedit-core/src/main/java/com/sk89q/worldedit/extension/platform/PlatformCommandManager.java, worldedit-core/src/main/java/com/sk89q/worldedit/world/chunk/AnvilChunk15.java, worldedit-core/src/main/java/com/sk89q/worldedit/world/chunk/AnvilChunk17.java, worldedit-core/src/main/java/com/sk89q/worldedit/world/chunk/AnvilChunk18.java, worldedit-core/src/main/java/com/sk89q/worldedit/world/chunk/PackedIntArrayReader.java, worldedit-core/src/main/java/com/sk89q/worldedit/world/storage/ChunkStoreHelper.java, worldedit-core/src/main/java/com/sk89q/worldedit/world/storage/TrueZipMcRegionChunkStore.java, worldedit-core/src/main/java/com/sk89q/worldedit/world/storage/ZippedMcRegionChunkStore.java
=> Fix //snapshot in 1.18 and re-implement biome/entity restoration

.github/workflows/build.yml
If it does work here too I'm happy.
=> Bump `actions/setup-java` to 3.0.0

worldedit-bukkit/adapters/adapter-1_18_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R2/PaperweightBlockMaterial.java, worldedit-bukkit/adapters/adapter-1_18_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R2/PaperweightPlatformAdapter.java, worldedit-bukkit/adapters/adapter-1_18_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R2/regen/PaperweightRegen.java
=> 1.18.2: Update SpigotNames to 1.18.2

worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_17_R1_2/regen/PaperweightRegen.java, worldedit-bukkit/adapters/adapter-1_18_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R2/PaperweightBlockMaterial.java, worldedit-bukkit/adapters/adapter-1_18_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R2/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_18_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R2/PaperweightGetBlocks.java, worldedit-bukkit/adapters/adapter-1_18_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R2/PaperweightPlatformAdapter.java, worldedit-bukkit/adapters/adapter-1_18_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R2/regen/PaperweightRegen.java, worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/BukkitBlockCategoryRegistry.java
More 1.18.2 stuff - Now using Holders for biomes and implementing missing stuff for regeneration
- [kind of] I tested my changes and approved their functionality.
=> 1.18.2 / Biome-Holders, regeneration

worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/NullExtent.java, worldedit-core/src/main/java/com/sk89q/worldedit/extent/NullExtent.java
=> Don't error when adding processors to NullExtent, simply do nothing

worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_17_R1_2/PaperweightPlatformAdapter.java
This was a copy paste issue preventing FAWE from working on 1.17 spigot.
=> Use correct class to look up lock field in 1.17

worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/pattern/BufferedPattern2DParser.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/pattern/BufferedPatternParser.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/function/mask/CachedMask.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/BufferedPattern.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/BufferedPattern2D.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/math/BlockVectorSet.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/math/LocalBlockVectorSet.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/util/collection/BlockVector3Set.java, worldedit-core/src/main/java/com/sk89q/worldedit/EditSession.java, worldedit-core/src/main/java/com/sk89q/worldedit/extension/input/ParserContext.java
=> Allow use of BlockVectorSet for large //line selections instead of LocalBlockVectorSet

README.adoc
=> Add jenkins to downloads list

.github/workflows/upload-release-assets.yml
Fixes https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/1749
This time addressing the issue properly.
=> Attach assets to GH releases

buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/CommonJavaConfig.kt, worldedit-bukkit/adapters/adapter-1_17_1/build.gradle.kts, worldedit-bukkit/adapters/adapter-1_18/build.gradle.kts, worldedit-bukkit/adapters/adapter-1_18_2/build.gradle.kts, worldedit-bukkit/build.gradle.kts
Update PaperMC repository and JavaDocs endpoint.
Update PaperMC repository and JavaDocs endpoint.
=> Update PaperMC repository URL

worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/LinearClipboard.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/block/AbstractFilterBlock.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/block/AbstractSingleFilterBlock.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/block/ArrayFilterBlock.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/block/CharFilterBlock.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/block/ExtentFilterBlock.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/block/FilterBlock.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/math/DelegateBlockVector3.java, worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/BlockArrayClipboard.java, worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/Clipboard.java, worldedit-core/src/main/java/com/sk89q/worldedit/math/BlockVector3.java
=> Implement biomes to filter blocks and use in Clipboard pasting

worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/BukkitBlockCommandSender.java
=> Command block messages should be sent on the main thread as it causes a block update

worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/regions/GriefPreventionFeature.java
=> fix: Run GriefPrevention region check in sync

worldedit-core/src/main/java/com/sk89q/worldedit/EditSessionBuilder.java
=> Processor should be added to queue, not extent

worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/Clipboard.java
=> The extent minY check in clipboard paste is un-needed as it is handled gracefully by FAWE

worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/mask/RichMaskParser.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/function/mask/BlockMaskBuilder.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/util/StringMan.java, worldedit-core/src/main/java/com/sk89q/worldedit/function/mask/BlockMask.java, worldedit-core/src/main/java/com/sk89q/worldedit/function/mask/MaskIntersection.java
=> Fixes to BlockMask and "char" masks

worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/Regenerator.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/util/collection/MemBlockSet.java, worldedit-core/src/main/java/com/sk89q/worldedit/regions/CuboidRegion.java
- Fixes IntellectualSites/PlotSquared#3683
=> Don't do the unbelievable bad use of a MutableBlockVector2 in the creation of a set

worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/pattern/RandomFullClipboardPatternParser.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/RandomFullClipboardPattern.java
=> Fix #fullcopy -r

worldedit-core/src/main/java/com/sk89q/worldedit/command/ClipboardCommands.java
=> Actually apply source mask when using //paste -m <mask>

worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_17_R1_2/regen/PaperweightRegen.java, worldedit-bukkit/adapters/adapter-1_18_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R2/regen/PaperweightRegen.java, worldedit-bukkit/adapters/adapter-1_19/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R1/regen/PaperweightRegen.java, worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/Regenerator.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/RegionCommands.java
=> Implement generation of biome decorations to //regen <biome> and add option for a random seed to be used

worldedit-core/src/main/java/com/sk89q/worldedit/EditSession.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/SelectionCommands.java, worldedit-core/src/main/java/com/sk89q/worldedit/extent/Extent.java
=> Support using //distr on console properly

build.gradle.kts
This should facilitate testing PRs a lot, especially ingame.
=> chore: Add runServer task

worldedit-core/src/main/java/com/fastasyncworldedit/core/command/tool/brush/SplineBrush.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/function/visitor/DFSRecursiveVisitor.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/function/visitor/DFSVisitor.java
=> Account for use of MutableBlockVector3 in Spline Brush

worldedit-core/src/main/java/com/sk89q/worldedit/command/SchematicCommands.java
=> Re-implement incremental schematic names in a folder

worldedit-core/src/main/java/com/sk89q/worldedit/command/UtilityCommands.java
=> Assume a file not being in a subdirectory of root means a symlink is used

worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/chunk/ChunkHolder.java
- ChunkHolder#recycle never offered itself
- ChunkSet#recycle was never called
- Don't recycle ChunkHolder after call completed as it may yet be re-used by the queue
=> Actually implement ChunkHolder/ChunkSet pools

worldedit-core/src/main/java/com/sk89q/worldedit/EditSession.java, worldedit-core/src/main/java/com/sk89q/worldedit/regions/CuboidRegion.java
=> Fix walls command on 1D/2D selection

worldedit-core/src/main/java/com/fastasyncworldedit/core/history/change/MutableEntityChange.java
=> Getting correct String from CompoundTag

worldedit-core/src/main/java/com/sk89q/worldedit/regions/CuboidRegion.java
=> Correct return type for CuboidRegion#getFaces() upstream compatibility

worldedit-core/src/main/java/com/fastasyncworldedit/core/util/MainUtil.java
Improve `MainUtil#copyFile` using modern methods.
=> Improve ``MainUtil#copyFile``

worldedit-bukkit/adapters/adapter-1_19/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_19_R1/PaperweightAdapter.java
Merge once the build is green.
=> Add 1.19.2

worldedit-core/src/main/java/com/fastasyncworldedit/core/util/TextureUtil.java
We should really find a way to automate these updates...
=> chore: Update assets to 1.19.2

worldedit-core/src/main/java/com/fastasyncworldedit/core/util/TextureUtil.java
(cherry picked from commit a8885a349a567849f6db29565cc65b14e3dab155)
=> Retrieve the latest asset release version automatically

.github/workflows/build.yml, worldedit-bukkit/build.gradle.kts
Fixes https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/1967
=> Release to Modrinth

worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/util/image/BukkitImageViewer.java, worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/BukkitPlayer.java, worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/BukkitPlayerBlockBag.java, worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/BukkitWorld.java
=> fix: Add items to a player's inventory on the main thread

worldedit-bukkit/adapters/adapter-1_18_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R2/regen/PaperweightRegen.java
=> Fix mappings issue with biome-based regen on 1.18.2

worldedit-core/src/main/java/com/fastasyncworldedit/core/history/changeset/AbstractChangeSet.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/history/changeset/FaweStreamChangeSet.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/internal/exception/FaweException.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/internal/exception/FaweSmallEditUnsupportedException.java
=> feat: Reduce any spam caused by exceptions thrown when writing history

worldedit-core/src/main/java/com/sk89q/worldedit/regions/AbstractRegion.java
=> fix: bring default min/max y in line with upstream in AbstractRegion

worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/BukkitWorld.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/wrappers/WorldWrapper.java
=> fix: move main-thread call to be implementation from WorldWrapper

worldedit-bukkit/adapters/adapter-1_19/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R1/PaperweightPlatformAdapter.java
Follow up for 2fe54a04b5d2b8cbb2a26947df610f3c8d4400ca
https://paste.helpch.at/enewocuwux.md
Untested yet
=> Fix error on latest paper while copying entities

worldedit-core/src/main/java/com/sk89q/worldedit/util/TreeGenerator.java
=> Fix Chorus-Plant tree type generation

worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/parser/DefaultBlockParser.java, worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/parser/DefaultItemParser.java
=> Feature: add "h" as alias for "hand" and "oh" for "offhand"

build.gradle.kts
=> Terminate process if `.git` folder does not exist

.github/workflows/build-pr.yml, .github/workflows/build.yml, .github/workflows/codeql.yml
Similar to PlotSquared, workflows are now split.
=> Split workflows

gradle/libs.versions.toml, worldedit-bukkit/build.gradle.kts, worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/WorldEditPlugin.java, worldedit-core/build.gradle.kts
Residence uses a non-standardized approach to build and distribute binaries, incompatible with the industry standard.
I plan to remove our integration based on the usage statistics.
=> Add metrics for Residence

Jenkinsfile
Used for https://ci.athion.net/job/FastAsyncWorldEdit-Pull-Requests/
=> Move Jenkinsfile from ps-v7 to general branch

worldedit-core/src/main/java/com/sk89q/worldedit/command/tool/FloatingTreeRemover.java
Allows to remove nether trees
Allows to remove nether trees
=> Add nether tress into floating tree remover

build.gradle.kts
Help our developer to test FAWE across different minecraft versions
Help our developer to test FAWE across different minecraft versions
=> Improve testability by adding more versions of runPaper to the build scripts

worldedit-core/src/main/java/com/fastasyncworldedit/core/configuration/Settings.java
Fixes #2183
Improve user experience with an explanation on creating an empty Disallowed-Blocks list
=> Add an explanation to Disallowed-Blocks Comment

worldedit-core/src/main/java/com/fastasyncworldedit/core/limit/FaweLimit.java
- Use correct values to retain unlimited status when combining limits
=> fix: correctly in initialise unlimited limit

worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/Regenerator.java
=> fix: create single threaded executor for use with non-concurrent generators

worldedit-core/src/main/java/com/fastasyncworldedit/core/limit/FaweLimit.java, worldedit-core/src/main/java/com/sk89q/worldedit/EditSessionBuilder.java
=> fix: fix universal disallowed blocks logic in limit and EditSession compilation

worldedit-core/src/main/java/com/fastasyncworldedit/core/command/SuggestInputParseException.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/mask/RichMaskParser.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/pattern/RichPatternParser.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/function/mask/BlockMaskBuilder.java, worldedit-core/src/main/java/com/sk89q/worldedit/world/block/BlockState.java, worldedit-core/src/main/java/com/sk89q/worldedit/world/block/BlockTypes.java
- Deprecate for removal methods using string message
- Fixes #2026
=> feat: allow captions in SuggestInputParseException

worldedit-core/src/main/java/com/fastasyncworldedit/core/util/WEManager.java
=> fix: only send invalid region messages with debug true

worldedit-core/src/main/java/com/sk89q/worldedit/command/BiomeCommands.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/BrushCommands.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/ChunkCommands.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/ClipboardCommands.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/GeneralCommands.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/GenerationCommands.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/HistorySubCommands.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/NavigationCommands.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/RegionCommands.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/SchematicCommands.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/SelectionCommands.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/SnapshotCommands.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/SnapshotUtilCommands.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/ToolUtilCommands.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/UtilityCommands.java
- Effectively fixes the very specific "issue" in #2223 I guess
- Use this opportunity to clean up the command classes a bit
=> feat: make more commands unqueued

worldedit-core/src/main/java/com/sk89q/worldedit/command/BrushCommands.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/SchematicCommands.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/tool/brush/ClipboardBrush.java
=> feat: add -r (random rotate) flag to schem load and clipboard brush

worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/PaperweightPlatformAdapter.java
Fixes #2263
This PR corrects `BlockEntity#remove` spigot mapping
=> Fix BlockEntity#remove spigot mapping

worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_17_R1_2/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_18_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R2/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_19/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R1/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_19_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R2/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/PaperweightFaweAdapter.java
=> feat: improve error when loading biomes

worldedit-core/src/main/java/com/fastasyncworldedit/core/Fawe.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/DiskOptimizedClipboard.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/util/task/KeyQueuedExecutorService.java, worldedit-core/src/main/java/com/sk89q/worldedit/entity/Player.java
- Addresses #2222 (hopefully fixes)
=> feat: implement a player-specific queue for clipboard IO tasks

worldedit-bukkit/adapters/adapter-1_19/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R1/PaperweightPlatformAdapter.java, worldedit-bukkit/adapters/adapter-1_19_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R2/PaperweightPlatformAdapter.java, worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/PaperweightPlatformAdapter.java, worldedit-bukkit/adapters/adapter-1_20/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R1/PaperweightPlatformAdapter.java
Fixes #2280 
Untested.
Fixes isues with mappings and adapter loading on spigot.
```[tasklist]
```
=> Set proper field access and use mappings for entities on spigot

worldedit-bukkit/src/test/java/com/sk89q/worldedit/bukkit/BukkitWorldTest.java, worldedit-core/src/main/java/com/sk89q/worldedit/util/TreeGenerator.java
- Fixes #2197
- Fixes https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/2288
=> feat: add new tree types to tree tool and brush

worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/NMSAdapter.java
=> fix: use new array when creating palette

worldedit-core/src/main/java/com/sk89q/worldedit/EditSessionBuilder.java
- Ensure history will actually always be closed if combine-stages is false
- Fixes #2148
=> fix: always return the changeset from EditSessionBuilder

worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/regions/TownyFeature.java
=> fix: towny max bounds are exclusive 

worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/chunk/ChunkHolder.java
- blocks could still be set to the ChunkHolder during a call
- create a new chunk SET in that case
- make cached get/set volatile to improve thread safety
=> fix: uncache the chunk SET at a better time in ChunkHolder to prevent "lost" changes

worldedit-core/src/main/java/com/sk89q/worldedit/EditSession.java
No major speed improvements, but sorta reduced memory footprint and quite large reductions in number of numeric calculations done
=> refactor: efficiency improvements to some editsession methods

worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/FaweBukkit.java, worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/regions/GriefPreventionFeature.java, worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/regions/ResidenceFeature.java, worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/regions/TownyFeature.java, worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/regions/plotsquared/PlotSquaredFeature.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/regions/FaweMask.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/regions/FaweMaskManager.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/util/WEManager.java
- Actually cache masks, even if the player has left the region
- Fix P2 isValid test for single plots
- Fixes #1946
- Fixes #2137
=> feat: improve (region) fawe mask handling

worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/pattern/RichPatternParser.java
=> feat: allow bracketless '%' pattern definition

worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/PaperweightGetBlocks.java, worldedit-bukkit/adapters/adapter-1_20/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R1/PaperweightGetBlocks.java
=> fix: ensure chunk is loaded when getting entities

worldedit-core/src/main/java/com/fastasyncworldedit/core/util/UpdateNotification.java
1. Use the modern HttpClient to access remote data
2. Use inbuilt timeout to ensure the connection is closed at some point.
3. Run code async to reduce effect on server startup time
4. (avoid URL constructor that will be deprecated in Java 21)
```[tasklist]
```
=> refactor: use HttpClient for update check

worldedit-core/src/main/java/com/fastasyncworldedit/core/configuration/Settings.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/util/TaskManager.java
- remove unused configuration options
=> chore: deprecate some methods that ought to be removed

worldedit-core/src/main/java/com/fastasyncworldedit/core/command/tool/brush/CommandBrush.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/command/tool/brush/ScatterCommand.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/BrushCommands.java
=> fix: fix command brush

worldedit-core/src/main/java/com/fastasyncworldedit/core/util/ProcessorTraverser.java, worldedit-core/src/main/java/com/sk89q/worldedit/EditSession.java
=> fix: fix adding/getting masks to/from MaskExtent when it is a processor

worldedit-core/src/main/java/com/fastasyncworldedit/core/Fawe.java, worldedit-core/src/main/java/com/sk89q/worldedit/LocalSession.java, worldedit-core/src/main/java/com/sk89q/worldedit/entity/Player.java
- another possible help towards the OverlappingFileLockException
=> feat: synchronise disk clipboard loading and deletion to clipboardLock

worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_17_R1_2/PaperweightPlatformAdapter.java, worldedit-bukkit/adapters/adapter-1_18_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R2/PaperweightPlatformAdapter.java, worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/PaperweightPlatformAdapter.java, worldedit-bukkit/adapters/adapter-1_20/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R1/PaperweightPlatformAdapter.java
- #2332 makes it seem like paper forgets to load a chunk sometimes
- resubmit chunk load request after a second to attempt to counter this
=> feat: re-submit chunk load request after 10s after checking world is loaded

worldedit-core/src/legacy/java/com/sk89q/worldedit/blocks/MobSpawnerBlock.java
=> fix: correct NBT for spawners

worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/pattern/TypeSwapPatternParser.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/TypeSwapPattern.java, worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/PatternFactory.java
=> feat: implement a new "type swap" pattern

worldedit-core/src/main/java/com/fastasyncworldedit/core/util/UpdateNotification.java
=> fix: don't warn on release build

worldedit-core/src/main/java/com/sk89q/worldedit/EditSessionBuilder.java
=> fix: disallowed regions can be length 0

buildSrc/src/main/kotlin/LibsConfig.kt, buildSrc/src/main/kotlin/PlatformConfig.kt
- Fixes https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/2423
- Fixes https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/2422
- Resolves https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/2421
Fixes #2423 
Fixes #2422 
Resolves #2421 
Addresses issues related to maven publish scm block
```[tasklist]
```
=> Addresses issues related to maven publish scm block

worldedit-core/src/main/java/com/fastasyncworldedit/core/command/tool/brush/InspectBrush.java
=> fix: add null check for block targetted with inspect brush

worldedit-core/src/main/java/com/sk89q/worldedit/function/entity/ExtentEntityCopy.java
=> Fix NullPointerException due to nullable source extent in ExtentEntityCopy

buildSrc/src/main/kotlin/CommonJavaConfig.kt
Building produced warnings about redirections. Updating the url avoids those warnings.
```[tasklist]
```
=> chore: update log4j2 javadoc url

.github/workflows/label-merge-conflicts.yaml
Supersedes manual checking like https://github.com/IntellectualSites/FastAsyncWorldEdit/pull/2461#issuecomment-1774014454
=> Label PRs with merge conflicts

worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/regen/PaperweightRegen.java
Mappings were wrong for that field, we tried to set a private final field with a different type.
```[tasklist]
```
=> Fix chunkSource mappings on 1.19.4

worldedit-core/src/main/java/com/sk89q/worldedit/LocalSession.java
Fixes #2488
When not on the main thread, we still call unlock for a lock operation we never called. Simply hiding it behind a main thread check again aligns it with the lock call.
```[tasklist]
```
=> Only unlock if previously locked

worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/regions/plotsquared/FaweDelegateRegionManager.java
=> fix: set biome biome on clear

worldedit-core/src/main/java/com/fastasyncworldedit/core/configuration/Settings.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/DiskOptimizedClipboard.java
- related to #2222
- effectively just a workaround as most people would not need to worry about locking the clipboard file
=> feat: add config option for if the DOC should lock the file channel

worldedit-bukkit/adapters/adapter-1_17_1/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_17_R1_2/PaperweightGetBlocks.java, worldedit-bukkit/adapters/adapter-1_18_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_18_R2/PaperweightGetBlocks.java, worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/PaperweightGetBlocks.java, worldedit-bukkit/adapters/adapter-1_20/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R1/PaperweightGetBlocks.java, worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightGetBlocks.java, worldedit-bukkit/adapters/adapter-1_20_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R3/PaperweightGetBlocks.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/chunk/ChunkHolder.java
=> fix:  always set createCopy status on chunk get as chunks are cached

worldedit-core/src/main/java/com/sk89q/worldedit/util/gson/GsonUtil.java, worldedit-core/src/main/java/com/sk89q/worldedit/util/gson/ItemTypeAdapter.java, worldedit-core/src/main/java/com/sk89q/worldedit/world/item/ItemType.java
- InternalId changes depending on {magic} so we should not store this value
- fixes #2589
=> fix: correctly (de)serialise ItemType

worldedit-core/src/main/java/com/fastasyncworldedit/core/util/MainUtil.java
- Added better error handling in case of non-2xx responses
- Create ImageInputStream (images did not load for me otherwise)
- Adds curl header to imgur requests (otherwise response will always be 429)
```[tasklist]
```
=> fix: imgur image resolution, image input stream reading

worldedit-core/src/main/java/com/sk89q/worldedit/command/SchematicCommands.java, worldedit-core/src/main/java/com/sk89q/worldedit/util/paste/ActorCallbackPaste.java, worldedit-core/src/main/java/com/sk89q/worldedit/util/paste/EngineHubPaste.java, worldedit-core/src/main/java/com/sk89q/worldedit/util/paste/PasteMetadata.java
A WE 7.3.0 feature from 2021, it's time to pull some upstream changes.
```[tasklist]
```
=> Integrate WE Schematic Share system

worldedit-core/src/main/java/com/sk89q/worldedit/world/block/BlockTypes.java
=> fix: add missing blocktypes and some minor cleanup

worldedit-core/src/main/java/com/fastasyncworldedit/core/configuration/Settings.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/GenerationCommands.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/RegionCommands.java
- also add unstuck to a couple of other commands
- closes #2675
=> feat: only unstuck a player if configured to do so

worldedit-bukkit/adapters/adapter-1_20_5/build.gradle.kts, worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/block/AbstractFilterBlock.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/block/ArrayFilterBlock.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/block/CharFilterBlock.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/block/FilterBlock.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/block/SingleFilterBlock.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/math/DelegateBlockVector3.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/math/MutableBlockVector3.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/math/MutableVector3.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/math/OffsetBlockVector3.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/math/Vector3Impl.java, worldedit-core/src/main/java/com/sk89q/worldedit/math/BlockVector2.java, worldedit-core/src/main/java/com/sk89q/worldedit/math/BlockVector3.java, worldedit-core/src/main/java/com/sk89q/worldedit/math/BlockVector3Imp.java, worldedit-core/src/main/java/com/sk89q/worldedit/math/Vector2.java, worldedit-core/src/main/java/com/sk89q/worldedit/math/Vector3.java, worldedit-core/src/main/java/com/sk89q/worldedit/util/Location.java
Basically, integrates the record updates from upstream in a kind of fitting matter (due to use of abstract classes only "simulated" records).
Started updating references to the now deprecated methods, but there are a few hundreds left - which can be addressed on the fly when working on other things or if someone want's to do that. Works right now, but will extend the amount of deprecation warnings quite a bit (as if that matters lol)
WorldGuard seems to run, and basic WE commands as well(?)
Fixes #2738
Partially addresses #2740
```[tasklist]
```
=> Fix compatibility with WorldGuard

worldedit-bukkit/adapters/adapter-1_20_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R4/PaperweightPlatformAdapter.java
Fixes an error reported multiple times (https://pastebin.com/hCSUPE8j)
Seems like the signature changed, tested the change locally and could paste normally without any error and chunks were sent
```[tasklist]
```
=> fix: ClassCastException on spigot

worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/regions/plotsquared/PlotSquaredFeature.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/IBatchProcessor.java, worldedit-core/src/main/java/com/sk89q/worldedit/regions/CuboidRegion.java
- fixes #2727
- fixes IntellectualSites/Plotsquared#4436
=> fix: correctly trim the max chunk section

worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/io/schematic/MinecraftStructure.java
=> fix: correclty create Minecraft Structure format schematics

worldedit-core/src/main/java/com/fastasyncworldedit/core/Fawe.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/configuration/Settings.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/limit/FaweLimit.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/WorldEditCommands.java
=> fix: take confirm-large from default limit for unlimited, add option to override

worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/regions/WorldGuardFeature.java, worldedit-core/src/main/java/com/sk89q/worldedit/regions/Region.java, worldedit-core/src/main/java/com/sk89q/worldedit/regions/RegionIntersection.java
=> fix: correctly process chunks when using worldguard region blacklists

worldedit-core/src/main/java/com/fastasyncworldedit/core/configuration/Config.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/configuration/Settings.java, worldedit-core/src/main/java/com/sk89q/worldedit/entity/Player.java
- Implement new annotation to settings that allows copying from an existing node to a new node
- fixes #2663
=> fix: extract new config option for deleting disk history on logout

worldedit-core/src/main/java/com/fastasyncworldedit/core/configuration/Config.java
=> fix: only write copied value if non null

worldedit-core/src/main/java/com/fastasyncworldedit/core/exception/OutsideWorldBoundsException.java, worldedit-core/src/main/java/com/sk89q/worldedit/WorldEdit.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/UtilityCommands.java, worldedit-core/src/main/java/com/sk89q/worldedit/internal/command/exception/WorldEditExceptionConverter.java, worldedit-core/src/main/resources/lang/strings.json
=> feat: implement graceful world bounds check where appropriate

worldedit-core/src/main/java/com/fastasyncworldedit/core/command/tool/scroll/Scroll.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/configuration/Settings.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/mask/RichMaskParser.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/platform/binding/ConsumeBindings.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/function/mask/BlockMaskBuilder.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/limit/FaweLimit.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/GeneralCommands.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/argument/FactoryConverter.java, worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/parser/mask/BlocksMaskParser.java, worldedit-core/src/main/java/com/sk89q/worldedit/scripting/CraftScriptContext.java
=> feat: add option to prevent parsing legacy blocks to the FaweLimit

build.gradle.kts, buildSrc/src/main/kotlin/CommonJavaConfig.kt, gradle/libs.versions.toml, settings.gradle.kts, worldedit-bukkit/adapters/adapter-1_21/build.gradle.kts, worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_21_R1/PaperweightAdapter.java, worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_21_R1/PaperweightDataConverters.java, worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_21_R1/PaperweightFakePlayer.java, worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_21_R1/PaperweightWorldNativeAccess.java, worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_21_R1/StaticRefraction.java, worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightBlockMaterial.java, worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightFaweWorldNativeAccess.java, worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightGetBlocks.java, worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightGetBlocks_Copy.java, worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightMapChunkUtil.java, worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightPlatformAdapter.java, worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightPostProcessor.java, worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightStarlightRelighter.java, worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightStarlightRelighterFactory.java, worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/nbt/PaperweightLazyCompoundTag.java, worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/regen/PaperweightRegen.java, worldedit-bukkit/build.gradle.kts
- support for Paper's new chunk gen system is out of scope for this PR
=> feat: implement 1.21

worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/ReadOnlyClipboard.java
=> fix: override min/max pos methods from SimpleClipboard

worldedit-core/src/main/java/com/fastasyncworldedit/core/math/BlockVectorSet.java
=> fix: use new index calculations for BlockVectorSet remove

worldedit-core/src/main/java/com/fastasyncworldedit/core/command/tool/brush/PopulateSchem.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/function/generator/SchemGen.java, worldedit-core/src/main/java/com/sk89q/worldedit/EditSession.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/BrushCommands.java, worldedit-core/src/main/java/com/sk89q/worldedit/extent/Extent.java
=> fix: improve SchemGen, allow null mask (reordered command args)

worldedit-core/src/main/java/com/fastasyncworldedit/core/util/MainUtil.java, worldedit-core/src/main/java/com/sk89q/worldedit/command/SchematicCommands.java, worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/io/ClipboardFormats.java
=> fix: correctly resolve file if extension is given

worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/DiskOptimizedClipboard.java, worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/LinearClipboard.java
I missed temporary changes that were WIP. Tested with filled chests and normal blocks.
```[tasklist]
```
=> Fix tile copying

worldedit-core/src/main/java/com/fastasyncworldedit/core/history/changeset/ChangeExchangeCoordinator.java
- prevent FAWE dying for a user if the reader thread dies
=> fix: add timeout to reading history from exchanger

worldedit-core/src/main/java/com/fastasyncworldedit/core/internal/simd/SimdSupport.java
`#existing` is e.g. implicitly used by `//replace` with only one argument. It's basically a "not air". It is also used in `#air` but negated, so supporting `InverseMask`s were the original mask can be vectorized is simple and useful.
```[tasklist]
```
=> Implement vectorization of #existing and inverse masks

worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/io/MCEditSchematicReader.java
=> fix: don't require WEOrigin / WEOffset in MCEdit schematics

worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_21_R1/PaperweightAdapter.java
Fixes #2954
Fixes incompatibilities after changes in CraftBukkit.
```[tasklist]
```
=> Use data version provided by MC

worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/chunk/ChunkHolder.java
=> Fix ChunkHolder tile set delegation

worldedit-core/src/legacy/java/com/sk89q/worldedit/blocks/LegacyBaseBlockWrapper.java, worldedit-core/src/legacy/java/com/sk89q/worldedit/blocks/MobSpawnerBlock.java, worldedit-core/src/legacy/java/com/sk89q/worldedit/blocks/SignBlock.java, worldedit-core/src/legacy/java/com/sk89q/worldedit/blocks/SkullBlock.java, worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/parser/DefaultBlockParser.java
=> fix: spawner type in pattern

worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/platform/binding/ProvideBindings.java
Fixes #3069
`//lazycopy` wasn't working due to that
```[tasklist]
```
=> Make EditSession available via Request again

worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightGetBlocks_Copy.java, worldedit-bukkit/adapters/adapter-1_20_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R3/PaperweightGetBlocks_Copy.java, worldedit-bukkit/adapters/adapter-1_20_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R4/PaperweightGetBlocks_Copy.java, worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightGetBlocks_Copy.java, worldedit-bukkit/adapters/adapter-1_21_3/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_3/PaperweightGetBlocks_Copy.java, worldedit-bukkit/adapters/adapter-1_21_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_4/PaperweightGetBlocks_Copy.java
The direct chunk coords in the LevelChunk are paper-only, so we should avoid them.
```[tasklist]
```
=> Restore spigot compatibility after #2356

worldedit-core/src/main/java/com/sk89q/worldedit/util/TreeGenerator.java
=> Add pale oak tree variants

.github/ISSUE_TEMPLATE/bug_report.yml
This pr adds 1.21.4 into issues template
```[tasklist]
```
=> Add 1.21.4 for bug reports

buildSrc/build.gradle.kts, worldedit-bukkit/adapters/adapter-1_21_4/build.gradle.kts, worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/io/FastSchematicWriterV3.java
Fixes #3160
Untested, as I can't get the project to build locally - don't see why it wouldn't work though (famous last words)
=> fix: saving of blocks with tile entity data in FAST_V3

worldedit-core/src/main/java/com/sk89q/worldedit/function/mask/ExistingBlockMask.java
This reduces the overhead of the `#existing` mask.
=> Improve #existing mask performance

worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/processor/lighting/NMSRelighter.java
=> fix: some fixes to NMSRelighter

build.gradle.kts, buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/LibsConfig.kt, buildSrc/src/main/kotlin/PlatformConfig.kt
=> ci: try yet another publishing plugin

worldedit-bukkit/adapters/adapter-1_20_2/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R2/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_20_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R3/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_20_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_20_R4/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_21/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_R1/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_21_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_4/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_21_5/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_5/PaperweightFaweAdapter.java, worldedit-bukkit/adapters/adapter-1_21_6/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_6/PaperweightFaweAdapter.java
=> feat: lazily resolve NBT on items

buildSrc/src/main/kotlin/CommonConfig.kt, gradle/libs.versions.toml
Update native Minecraft dependencies matching the versions we support.
=> Update native Minecraft dependencies

worldedit-bukkit/adapters/adapter-1_21_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_21_4/PaperweightPlatformAdapter.java
=> fix: 1.21.4 entityManager obf is O not N

buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/LibsConfig.kt, buildSrc/src/main/kotlin/PlatformConfig.kt
Reverts commit a6da5957bf11f5a6b0317506af02fd5645cc926f. "Tree-Shaking" and shading itself doesn't seem to work reliable. Needs further investigation, but a working build is more important now.
=> hotfix: revert shadow plugin upgrade

README.md, worldedit-bukkit/src/main/resources/plugin.yml, worldedit-cli/build.gradle.kts, worldedit-core/src/main/java/com/fastasyncworldedit/core/util/UpdateNotification.java, worldedit-core/src/main/resources/lang/strings.json
=> Update a few links
